// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-rpc-ts@v0.1.0 (hash dd0e1d94)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

import * as vdlTypes from "./types.js";

/**
 * VDLProcedures lists every generated procedure definition with preserved schema metadata.
 * Use it for introspection, tracing, and building operation-aware tooling.
 */
export const VDLProcedures: OperationDefinition[] = [
  {
    "rpcName": "Database",
    "name": "query",
    "type": "proc",
    "path": "/Database/query",
    "annotations": []
  },
  {
    "rpcName": "System",
    "name": "health",
    "type": "proc",
    "path": "/System/health",
    "annotations": []
  },
  {
    "rpcName": "System",
    "name": "session",
    "type": "proc",
    "path": "/System/session",
    "annotations": []
  },
  {
    "rpcName": "System",
    "name": "status",
    "type": "proc",
    "path": "/System/status",
    "annotations": []
  },
] as const;

/**
 * VDLStreams lists every generated stream definition with preserved schema metadata.
 * Use it for introspection, tracing, and building operation-aware tooling.
 */
export const VDLStreams: OperationDefinition[] = [

] as const;

/**
 * VDLPaths maps rpcName -> operationName -> relative URL path.
 * Useful when wiring custom transports or inspecting generated routes.
 */
export const VDLPaths = {
  Database: {
    query: "/Database/query",
  },
  System: {
    health: "/System/health",
    session: "/System/session",
    status: "/System/status",
  },
} as const;
/**
 * Supported RPC operation kinds.
 */
export type OperationType = "proc" | "stream";

/**
 * JSON-compatible value used for annotation arguments preserved in catalogs.
 */
export type AnnotationValue =
  | string
  | number
  | boolean
  | null
  | AnnotationValue[]
  | { [key: string]: AnnotationValue };

/**
 * Preserved annotation metadata for generated RPC operations.
 */
export interface OperationAnnotation {
  /** Annotation name without the @ prefix. */
  name: string;
  /** Optional resolved annotation argument. */
  argument?: AnnotationValue;
}

/**
 * Runtime description of a generated procedure or stream.
 */
export interface OperationDefinition {
  /** RPC service name as declared in VDL. */
  rpcName: string;
  /** Operation name as declared in VDL. */
  name: string;
  /** Operation kind. */
  type: OperationType;
  /** Stable relative path appended to the configured base URL. */
  path: string;
  /** Non-marker annotations preserved from the VDL schema. */
  annotations: OperationAnnotation[];
}

/**
 * Empty-object helper used for procedures or streams that omit input and/or output.
 */
export type Void = Record<string, never>;

/**
 * Runtime helpers for the generated Void shape.
 */
export const Void = {
  /** Parses a JSON string into an empty object. */
  parse(json: string): Void {
    const input = JSON.parse(json) as unknown;
    const error = Void.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Void.hydrate(input as Void);
  },

  /** Validates that the provided value is an empty object. */
  validate(input: unknown, path = "Void"): string | null {
    if (typeof input !== "object" || input === null || Array.isArray(input)) {
      const got = input === null ? "null" : Array.isArray(input) ? "array" : typeof input;
      return path + ": expected object, got " + got;
    }

    if (Object.keys(input as Record<string, unknown>).length > 0) {
      return path + ": expected empty object, got non-empty object";
    }

    return null;
  },

  /** Hydrates an empty object into the canonical runtime representation. */
  hydrate(_input: Void): Void {
    return {};
  },
} as const;

/**
 * Response envelope returned by VDL procedures and yielded by VDL streams.
 * 
 * @typeParam T - The concrete type of the successful response output.
 */
export type Response<T> =
  /** Successful response */
  | {
      /** Indicates whether the RPC call was successful. */
      ok: true;
      /** The successful output payload. */
      output: T;
      /** Not present when the call is successful. */
      error?: never;
    }
  /** Error response */
  | {
      /** Indicates whether the RPC call failed. */
      ok: false;
      /** Not present when the call fails. */
      output?: never;
      /** Structured error payload. */
      error: VdlError;
    };

/**
 * Structured error type used throughout the VDL ecosystem.
 *
 * It provides structured information about errors that occur within the system,
 * enabling consistent error handling across servers and clients.
 *
 * Fields:
 *   - Message: A human-readable description of the error.
 *   - Category: Optional. Categorizes the error by its nature or source (e.g., "ValidationError", "DatabaseError").
 *   - Code: Optional. A machine-readable identifier for the specific error condition (e.g., "INVALID_EMAIL").
 *   - Details: Optional. Additional information about the error.
 */
export class VdlError extends Error {
  public readonly category?: string;
  public readonly code?: string;
  public readonly details?: Record<string, unknown>;

  constructor(options: {
    /**
     * Message provides a human-readable description of the error.
     *
     * This message can be displayed to end-users or used for logging and debugging purposes.
     *
     * Use Cases:
     *   1. If localization is not implemented, Message can be directly shown to the user to inform them of the issue.
     *   2. Developers can use Message in logs to diagnose problems during development or in production.
     */
    message: string;
    /**
     * Category categorizes the error by its nature or source.
     *
     * Examples:
     *   - "ValidationError" for input validation errors.
     *   - "DatabaseError" for errors originating from database operations.
     *   - "AuthenticationError" for authentication-related issues.
     *
     * Use Cases:
     *   1. In middleware, you can use Category to determine how to handle the error.
     *      For instance, you might log "InternalError" types and return a generic message to the client.
     *   2. Clients can inspect the Category to decide whether to prompt the user for action,
     *      such as re-authentication if the Category is "AuthenticationError".
     */
    category?: string;
    /**
     * Code is a machine-readable identifier for the specific error condition.
     *
     * Examples:
     *   - "INVALID_EMAIL" when an email address fails validation.
     *   - "USER_NOT_FOUND" when a requested user does not exist.
     *   - "RATE_LIMIT_EXCEEDED" when a client has made too many requests.
     *
     * Use Cases:
     *   1. Clients can map Codes to localized error messages for internationalization (i18n),
     *      displaying appropriate messages based on the user's language settings.
     *   2. Clients or middleware can implement specific logic based on the Code,
     *      such as retry mechanisms for "TEMPORARY_FAILURE" or showing captcha for "RATE_LIMIT_EXCEEDED".
     */
    code?: string;
    /**
     * Details contains optional additional information about the error.
     *
     * This field can include any relevant data that provides more context about the error.
     * The contents should be serializable to JSON.
     *
     * Use Cases:
     *   1. Providing field-level validation errors, e.g., Details could be:
     *      {"fields": {"email": "Email is invalid", "password": "Password is too short"}}
     *   2. Including diagnostic information such as timestamps, request IDs, or stack traces
     *      (ensure sensitive information is not exposed to clients).
     */
    details?: Record<string, unknown>;
  }) {
    super(options.message);
    this.name = "VdlError"; // Easier stack-trace filtering.
    this.category = options.category;
    this.code = options.code;
    this.details = options.details;
    Object.setPrototypeOf(this, new.target.prototype); // Maintains proper prototype chain when targeting ES5.
  }

  /** Serialises the error including all optional fields. */
  toJSON(): Record<string, unknown> {
    return {
      message: this.message,
      ...(this.category ? { category: this.category } : {}),
      ...(this.code ? { code: this.code } : {}),
      ...(this.details ? { details: this.details } : {}),
    };
  }
}

/**
 * Normalizes arbitrary error inputs into a VdlError instance.
 */
export function asError(err: unknown): VdlError {
  if (err instanceof VdlError) {
    return err;
  }

  if (err instanceof Error) {
    return new VdlError({ message: err.message });
  }

  return new VdlError({ message: String(err) });
}

/**
 * Convenience helper for missing-field validation errors.
 */
function errorMissingRequiredField(message: string): VdlError {
  return new VdlError({
    message,
    category: "ValidationError",
    code: "MISSING_REQUIRED_FIELD",
  });
}

/**
 * Sleeps for the given number of milliseconds.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
/**
 * Context provided to a retry decider.
 */
export interface RetryDecisionContext {
  /** Current attempt number, starting at 1. */
  attempt: number;
  /** Maximum configured attempts. */
  maxAttempts: number;
  /** Error produced by the current attempt. */
  error: VdlError;
  /** Original input payload. */
  input: unknown;
  /** Resolved operation metadata, including annotations. */
  operation?: OperationDefinition;
  /** Whether the generated runtime would retry without custom logic. */
  defaultRetryable: boolean;
}

/**
 * Context provided to a reconnect decider.
 */
export interface ReconnectDecisionContext {
  /** Current reconnect attempt number, starting at 1. */
  attempt: number;
  /** Maximum configured reconnect attempts. */
  maxAttempts: number;
  /** Error that triggered the reconnect evaluation. */
  error: VdlError;
  /** Original subscription input payload. */
  input: unknown;
  /** Resolved operation metadata, including annotations. */
  operation?: OperationDefinition;
  /** Calculated delay before the next reconnect attempt. */
  delayMs: number;
  /** Whether the generated runtime would reconnect without custom logic. */
  defaultReconnectable: boolean;
}

/**
 * Controls automatic retry behavior for procedure calls.
 *
 * When a request fails due to network errors, timeouts, or 5xx HTTP status codes,
 * the client can automatically retry using exponential backoff.
 */
export interface RetryConfig {
  maxAttempts: number;
  initialDelayMs: number;
  maxDelayMs: number;
  delayMultiplier: number;
  jitter: number;
  shouldRetry?: (context: RetryDecisionContext) => boolean | Promise<boolean>;
}

/**
 * Controls request timeout behavior.
 *
 * If the server does not respond within the configured timeout, the request is aborted
 * and may be retried according to the effective retry configuration.
 */
export interface TimeoutConfig {
  timeoutMs: number;
}

/**
 * Controls automatic reconnection behavior for streams.
 *
 * When a stream connection is lost due to network issues or server errors,
 * the client can automatically attempt to reconnect with exponential backoff.
 */
export interface ReconnectConfig {
  maxAttempts: number;
  initialDelayMs: number;
  maxDelayMs: number;
  delayMultiplier: number;
  jitter: number;
  shouldReconnect?: (
    context: ReconnectDecisionContext,
  ) => boolean | Promise<boolean>;
}

/**
 * A function that adds or modifies headers before each request.
 *
 * Header providers are executed in this order: global, RPC-level, operation-level.
 * They run before every request attempt, including retries and reconnects.
 */
export type HeaderProvider = (
  headers: Record<string, string>,
) => void | Promise<void>;

/**
 * Metadata about the current RPC request, passed to interceptors.
 */
export interface RequestInfo {
  rpcName: string;
  operationName: string;
  input: unknown;
  type: OperationType;
  operation?: OperationDefinition;
}

/** Final function invoked by the interceptor chain. */
export type Invoker = (req: RequestInfo) => Promise<Response<unknown>>;

/** Request interceptor used by generated clients. */
export type Interceptor = (
  req: RequestInfo,
  next: Invoker,
) => Promise<Response<unknown>>;

/**
 * Minimal interface for a fetch response.
 * Compatible with the standard Fetch API and most polyfills.
 */
export interface FetchLikeResponse {
  ok: boolean;
  status: number;
  body?: ReadableStream<Uint8Array> | null;
  json(): Promise<any>;
  text(): Promise<string>;
}

/**
 * Minimal interface for a fetch function.
 * Compatible with the standard Fetch API, node-fetch, and most polyfills.
 */
export type FetchLike = (input: any, init?: any) => Promise<FetchLikeResponse>;

/**
 * Default retry config: no retries (single attempt).
 */
const defaultRetryConfig: RetryConfig = {
  maxAttempts: 1,
  initialDelayMs: 0,
  maxDelayMs: 0,
  delayMultiplier: 1,
  jitter: 0.2,
};

/**
 * Default timeout: 30 seconds.
 */
const defaultTimeoutConfig: TimeoutConfig = {
  timeoutMs: 30000,
};

/**
 * Default reconnect config for streams.
 */
const defaultReconnectConfig: ReconnectConfig = {
  maxAttempts: 30,
  initialDelayMs: 1000,
  maxDelayMs: 30000,
  delayMultiplier: 1.5,
  jitter: 0.2,
};

/** Default maximum message size for streams: 4MB. */
const defaultMaxMessageSize = 4 * 1024 * 1024;

/**
 * Adds random jitter to a delay to prevent thundering herd effects.
 */
function applyJitter(delayMs: number, jitterFactor: number): number {
  if (jitterFactor <= 0) {
    return delayMs;
  }

  const boundedJitter = Math.min(jitterFactor, 1);
  const delta = delayMs * boundedJitter;
  const min = Math.max(0, delayMs - delta);
  const max = delayMs + delta;
  return min + Math.random() * (max - min);
}

/**
 * Calculates exponential backoff delay for retry attempts.
 */
function calculateBackoff(config: RetryConfig, attempt: number): number {
  let delay = config.initialDelayMs;
  for (let index = 1; index < attempt; index += 1) {
    delay *= config.delayMultiplier;
  }
  if (delay > config.maxDelayMs) {
    delay = config.maxDelayMs;
  }
  return applyJitter(delay, config.jitter);
}

/**
 * Calculates exponential backoff delay for stream reconnection attempts.
 */
function calculateReconnectBackoff(
  config: ReconnectConfig,
  attempt: number,
): number {
  let delay = config.initialDelayMs;
  for (let index = 1; index < attempt; index += 1) {
    delay *= config.delayMultiplier;
  }
  if (delay > config.maxDelayMs) {
    delay = config.maxDelayMs;
  }
  return applyJitter(delay, config.jitter);
}

/**
 * Normalizes retry config input into safe runtime values.
 */
function normalizeRetryConfig(
  config: Partial<RetryConfig>,
  defaultAttempts = 1,
): RetryConfig {
  return {
    maxAttempts: Math.max(1, config.maxAttempts ?? defaultAttempts),
    initialDelayMs: Math.max(0, config.initialDelayMs ?? 0),
    maxDelayMs: Math.max(0, config.maxDelayMs ?? 0),
    delayMultiplier: Math.max(1, config.delayMultiplier ?? 1),
    jitter: Math.max(0, Math.min(1, config.jitter ?? 0.2)),
    ...(config.shouldRetry ? { shouldRetry: config.shouldRetry } : {}),
  };
}

/**
 * Normalizes timeout config input into safe runtime values.
 */
function normalizeTimeoutConfig(config: Partial<TimeoutConfig>): TimeoutConfig {
  return {
    timeoutMs: Math.max(0, config.timeoutMs ?? defaultTimeoutConfig.timeoutMs),
  };
}

/**
 * Normalizes reconnect config input into safe runtime values.
 */
function normalizeReconnectConfig(
  config: Partial<ReconnectConfig>,
  defaultAttempts = 30,
): ReconnectConfig {
  return {
    maxAttempts: Math.max(0, config.maxAttempts ?? defaultAttempts),
    initialDelayMs: Math.max(
      0,
      config.initialDelayMs ?? defaultReconnectConfig.initialDelayMs,
    ),
    maxDelayMs: Math.max(
      0,
      config.maxDelayMs ?? defaultReconnectConfig.maxDelayMs,
    ),
    delayMultiplier: Math.max(
      1,
      config.delayMultiplier ?? defaultReconnectConfig.delayMultiplier,
    ),
    jitter: Math.max(
      0,
      Math.min(1, config.jitter ?? defaultReconnectConfig.jitter),
    ),
    ...(config.shouldReconnect
      ? { shouldReconnect: config.shouldReconnect }
      : {}),
  };
}

// =============================================================================
// Internal Client
// =============================================================================

/**
 * Core HTTP client engine used by generated VDL client wrappers.
 *
 * This class handles request execution, retry logic, timeout handling,
 * stream connections, header providers, and interceptors.
 *
 * Do not instantiate directly. Use the generated client builder.
 *
 * @internal
 */
class internalClient {
  /** Base URL for all requests (trailing slashes are stripped). */
  private baseURL: string;

  /** The fetch implementation used for HTTP requests. */
  private fetchFn: FetchLike;

  /**
   * Registry of valid operations.
   * Structure: rpcName → operationName → OperationType
   * Used to validate requests and fail fast on typos.
   */
  private operationDefs: Map<string, Map<string, OperationDefinition>>;

  // ---------------------------------------------------------------------------
  // Dynamic Components
  // ---------------------------------------------------------------------------

  /** Global header providers applied to all requests. */
  private headerProviders: HeaderProvider[] = [];

  /** Interceptors applied to all requests (in registration order). */
  private interceptors: Interceptor[] = [];

  /** RPC-specific header providers. Key: rpcName. */
  private rpcHeaderProviders: Map<string, HeaderProvider[]> = new Map();

  // ---------------------------------------------------------------------------
  // Global Default Configurations
  // ---------------------------------------------------------------------------

  private globalRetryConf: RetryConfig | null = null;
  private globalTimeoutConf: TimeoutConfig | null = null;
  private globalReconnectConf: ReconnectConfig | null = null;
  private globalMaxMessageSize: number = 0;

  // ---------------------------------------------------------------------------
  // Per-RPC Default Configurations
  // ---------------------------------------------------------------------------

  private rpcRetryConf: Map<string, RetryConfig> = new Map();
  private rpcTimeoutConf: Map<string, TimeoutConfig> = new Map();
  private rpcReconnectConf: Map<string, ReconnectConfig> = new Map();
  private rpcMaxMessageSize: Map<string, number> = new Map();

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------

  /**
   * Creates a new internal client.
   *
   * @throws If required runtime dependencies are missing.
   * @throws If no fetch implementation is available.
   */
  constructor(
    baseURL: string,
    procDefs: OperationDefinition[],
    streamDefs: OperationDefinition[],
    opts: internalClientOption[],
  ) {
    this.verifyRuntimeDeps();

    this.baseURL = baseURL.replace(/[/]+$/gu, "");
    this.fetchFn = (globalThis.fetch ?? null) as FetchLike;
    this.operationDefs = new Map();

    const ensureRPC = (rpcName: string) => {
      if (!this.operationDefs.has(rpcName)) {
        this.operationDefs.set(rpcName, new Map());
      }
    };

    for (const def of procDefs) {
      ensureRPC(def.rpcName);
      this.operationDefs.get(def.rpcName)?.set(def.name, def);
    }

    for (const def of streamDefs) {
      ensureRPC(def.rpcName);
      this.operationDefs.get(def.rpcName)?.set(def.name, def);
    }

    for (const applyOption of opts) {
      applyOption(this);
    }

    if (!this.fetchFn) {
      throw new Error(
        "globalThis.fetch is undefined. Provide a custom fetch with withCustomFetch().",
      );
    }
  }

  /**
   * Verifies that required runtime APIs are available.
   */
  private verifyRuntimeDeps() {
    const missing: string[] = [];

    if (typeof AbortController !== "function") {
      missing.push("AbortController");
    }
    if (typeof ReadableStream === "undefined") {
      missing.push("ReadableStream");
    }
    if (typeof TextDecoder !== "function") {
      missing.push("TextDecoder");
    }

    if (missing.length > 0) {
      throw new Error(
        "Missing required runtime dependencies: " +
          missing.join(", ") +
          ". Install the necessary polyfills or use a compatible environment.",
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Configuration Setters (called by builder options)
  // ---------------------------------------------------------------------------

  /** Sets a custom fetch implementation. */
  setFetch(fetchFn: FetchLike): void {
    this.fetchFn = fetchFn;
  }

  /** Adds a global header provider. */
  addHeaderProvider(provider: HeaderProvider): void {
    this.headerProviders.push(provider);
  }

  /** Adds an interceptor to the chain. */
  addInterceptor(interceptor: Interceptor): void {
    this.interceptors.push(interceptor);
  }

  /** Sets the global default retry configuration. */
  setGlobalRetryConfig(conf: RetryConfig): void {
    this.globalRetryConf = normalizeRetryConfig(conf, conf.maxAttempts);
  }

  /** Sets the global default timeout configuration. */
  setGlobalTimeoutConfig(conf: TimeoutConfig): void {
    this.globalTimeoutConf = normalizeTimeoutConfig(conf);
  }

  /** Sets the global default reconnect configuration for streams. */
  setGlobalReconnectConfig(conf: ReconnectConfig): void {
    this.globalReconnectConf = normalizeReconnectConfig(conf, conf.maxAttempts);
  }

  /** Sets the global default maximum message size for streams. */
  setGlobalMaxMessageSize(size: number): void {
    this.globalMaxMessageSize = size;
  }

  // ---------------------------------------------------------------------------
  // Per-RPC Configuration Setters
  // ---------------------------------------------------------------------------

  /** Sets the default retry config for a specific RPC. */
  setRPCRetryConfig(rpcName: string, conf: RetryConfig) {
    this.rpcRetryConf.set(rpcName, conf);
  }

  /** Sets the default timeout config for a specific RPC. */
  setRPCTimeoutConfig(rpcName: string, conf: TimeoutConfig) {
    this.rpcTimeoutConf.set(rpcName, conf);
  }

  /** Sets the default reconnect config for a specific RPC. */
  setRPCReconnectConfig(rpcName: string, conf: ReconnectConfig) {
    this.rpcReconnectConf.set(rpcName, conf);
  }

  /** Sets the default max message size for a specific RPC. */
  setRPCMaxMessageSize(rpcName: string, size: number) {
    this.rpcMaxMessageSize.set(rpcName, size);
  }

  /** Adds a header provider for a specific RPC. */
  setRPCHeaderProvider(rpcName: string, provider: HeaderProvider) {
    if (!this.rpcHeaderProviders.has(rpcName)) {
      this.rpcHeaderProviders.set(rpcName, []);
    }
    this.rpcHeaderProviders.get(rpcName)?.push(provider);
  }

  /**
   * Resolves one operation definition and verifies its expected kind.
   */
  private getOperation(
    rpcName: string,
    operationName: string,
    expectedType: OperationType,
  ): OperationDefinition | undefined {
    const operation = this.operationDefs.get(rpcName)?.get(operationName);
    if (!operation || operation.type !== expectedType) {
      return undefined;
    }
    return operation;
  }

  /**
   * Resolves the effective retry configuration for a request.
   * Priority: operation-level > RPC-level > global > built-in defaults.
   */
  private mergeRetryConfig(
    rpcName: string,
    opConf?: RetryConfig,
  ): RetryConfig {
    return {
      ...defaultRetryConfig,
      ...(this.globalRetryConf ?? {}),
      ...(this.rpcRetryConf.get(rpcName) ?? {}),
      ...(opConf ?? {}),
      ...(opConf?.shouldRetry
        ? { shouldRetry: opConf.shouldRetry }
        : this.rpcRetryConf.get(rpcName)?.shouldRetry
          ? { shouldRetry: this.rpcRetryConf.get(rpcName)?.shouldRetry }
        : this.globalRetryConf?.shouldRetry
          ? { shouldRetry: this.globalRetryConf.shouldRetry }
          : {}),
    };
  }

  /**
   * Resolves the effective timeout configuration for a request.
   * Priority: operation-level > RPC-level > global > built-in defaults.
   */
  private mergeTimeoutConfig(
    rpcName: string,
    opConf?: TimeoutConfig,
  ): TimeoutConfig {
    return {
      ...defaultTimeoutConfig,
      ...(this.globalTimeoutConf ?? {}),
      ...(this.rpcTimeoutConf.get(rpcName) ?? {}),
      ...(opConf ?? {}),
    };
  }

  /**
   * Resolves the effective reconnect configuration for a stream.
   * Priority: operation-level > RPC-level > global > built-in defaults.
   */
  private mergeReconnectConfig(
    rpcName: string,
    opConf?: ReconnectConfig,
  ): ReconnectConfig {
    return {
      ...defaultReconnectConfig,
      ...(this.globalReconnectConf ?? {}),
      ...(this.rpcReconnectConf.get(rpcName) ?? {}),
      ...(opConf ?? {}),
      ...(opConf?.shouldReconnect
        ? { shouldReconnect: opConf.shouldReconnect }
        : this.rpcReconnectConf.get(rpcName)?.shouldReconnect
          ? {
              shouldReconnect:
                this.rpcReconnectConf.get(rpcName)?.shouldReconnect,
            }
        : this.globalReconnectConf?.shouldReconnect
          ? { shouldReconnect: this.globalReconnectConf.shouldReconnect }
          : {}),
    };
  }

  /**
   * Resolves the effective maximum message size for a stream.
   * Priority: operation-level > RPC-level > global > built-in defaults.
   */
  private mergeMaxMessageSize(rpcName: string, opSize?: number): number {
    if (opSize && opSize > 0) {
      return opSize;
    }

    if (this.rpcMaxMessageSize.has(rpcName)) {
      const rpcSize = this.rpcMaxMessageSize.get(rpcName);
      if (rpcSize && rpcSize > 0) {
        return rpcSize;
      }
    }

    if (this.globalMaxMessageSize > 0) {
      return this.globalMaxMessageSize;
    }

    return defaultMaxMessageSize;
  }

  /**
   * Applies all header providers to a request's headers.
   * Order: global providers -> RPC providers -> operation providers.
   */
  private async applyHeaders(
    rpcName: string,
    headers: Record<string, string>,
    opHeaderProviders: HeaderProvider[],
  ): Promise<void> {
    for (const provider of this.headerProviders) {
      await provider(headers);
    }

    const rpcProviders = this.rpcHeaderProviders.get(rpcName) ?? [];
    for (const provider of rpcProviders) {
      await provider(headers);
    }

    for (const provider of opHeaderProviders) {
      await provider(headers);
    }
  }

  /**
   * Executes the interceptor chain around the provided invoker.
   */
  private async executeChain(
    reqInfo: RequestInfo,
    invoker: Invoker,
  ): Promise<Response<unknown>> {
    let next = invoker;
    for (let index = this.interceptors.length - 1; index >= 0; index -= 1) {
      const current = this.interceptors[index];
      const previousNext = next;
      next = (req) => current(req, previousNext);
    }
    return next(reqInfo);
  }

  /**
   * Evaluates whether the current failure should trigger another attempt.
   */
  private async shouldRetry(
    config: RetryConfig,
    context: RetryDecisionContext,
  ): Promise<boolean> {
    if (!config.shouldRetry) {
      return context.defaultRetryable;
    }

    return await config.shouldRetry(context);
  }

  /**
   * Evaluates whether the current stream failure should trigger reconnect.
   */
  private async shouldReconnect(
    config: ReconnectConfig,
    context: ReconnectDecisionContext,
  ): Promise<boolean> {
    if (!config.shouldReconnect) {
      return context.defaultReconnectable;
    }

    return await config.shouldReconnect(context);
  }

  /**
   * Executes one procedure call with retries, timeout, headers, and interceptors.
   */
  async callProc(
    rpcName: string,
    procName: string,
    input: unknown,
    opHeaderProviders: HeaderProvider[],
    opRetryConf?: RetryConfig,
    opTimeoutConf?: TimeoutConfig,
    opSignal?: AbortSignal,
  ): Promise<Response<any>> {
    if (opSignal?.aborted) {
      return {
        ok: false,
        error: new VdlError({
          message: "Request aborted",
          category: "ClientError",
          code: "ABORTED",
        }),
      };
    }

    const operation = this.getOperation(rpcName, procName, "proc");
    const reqInfo: RequestInfo = {
      rpcName,
      operationName: procName,
      input,
      type: "proc",
      operation,
    };

    const invoker: Invoker = async (req) => {
      if (!operation) {
        return {
          ok: false,
          error: new VdlError({
            message:
              req.rpcName +
              "." +
              req.operationName +
              " procedure not found in schema",
            category: "ClientError",
            code: "INVALID_PROC",
            details: { rpc: req.rpcName, procedure: req.operationName },
          }),
        };
      }

      let payload: string;
      try {
        payload = req.input == null ? "{}" : JSON.stringify(req.input);
      } catch (error) {
        return {
          ok: false,
          error: new VdlError({
            message:
              "Failed to encode input for " +
              req.rpcName +
              "." +
              req.operationName +
              ": " +
              String(error),
            category: "ClientError",
            code: "ENCODE_INPUT",
          }),
        };
      }

      const retryConf = this.mergeRetryConfig(req.rpcName, opRetryConf);
      const timeoutConf = this.mergeTimeoutConfig(req.rpcName, opTimeoutConf);
      const url = this.baseURL + "/" + req.rpcName + "/" + req.operationName;
      let lastError: VdlError | null = null;

      for (let attempt = 1; attempt <= retryConf.maxAttempts; attempt += 1) {
        if (opSignal?.aborted) {
          return {
            ok: false,
            error: new VdlError({
              message: "Request aborted",
              category: "ClientError",
              code: "ABORTED",
            }),
          };
        }

        const abortController = new AbortController();
        let timeoutId: ReturnType<typeof setTimeout> | undefined;
        const onExternalAbort = () => abortController.abort();
        opSignal?.addEventListener("abort", onExternalAbort);

        try {
          if (timeoutConf.timeoutMs > 0) {
            timeoutId = setTimeout(
              () => abortController.abort(),
              timeoutConf.timeoutMs,
            );
          }

          const headers: Record<string, string> = {
            "content-type": "application/json",
            accept: "application/json",
          };

          try {
            await this.applyHeaders(req.rpcName, headers, opHeaderProviders);
          } catch (error) {
            if (timeoutId !== undefined) {
              clearTimeout(timeoutId);
            }
            opSignal?.removeEventListener("abort", onExternalAbort);
            return { ok: false, error: asError(error) };
          }

          const fetchResponse = await this.fetchFn(url, {
            method: "POST",
            headers,
            body: payload,
            signal: abortController.signal,
          });

          if (timeoutId !== undefined) {
            clearTimeout(timeoutId);
          }
          opSignal?.removeEventListener("abort", onExternalAbort);

          if (fetchResponse.status >= 500) {
            const error = new VdlError({
              message:
                "Unexpected HTTP status: " + String(fetchResponse.status),
              category: "HTTPError",
              code: "BAD_STATUS",
              details: { status: fetchResponse.status },
            });
            const canRetry =
              attempt < retryConf.maxAttempts &&
              (await this.shouldRetry(retryConf, {
                attempt,
                maxAttempts: retryConf.maxAttempts,
                error,
                input,
                operation,
                defaultRetryable: true,
              }));

            if (canRetry) {
              lastError = error;
              await sleep(calculateBackoff(retryConf, attempt));
              continue;
            }

            return { ok: false, error };
          }

          if (!fetchResponse.ok) {
            const error = new VdlError({
              message:
                "Unexpected HTTP status: " + String(fetchResponse.status),
              category: "HTTPError",
              code: "BAD_STATUS",
              details: { status: fetchResponse.status },
            });
            const canRetry =
              attempt < retryConf.maxAttempts &&
              (await this.shouldRetry(retryConf, {
                attempt,
                maxAttempts: retryConf.maxAttempts,
                error,
                input,
                operation,
                defaultRetryable: false,
              }));

            if (canRetry) {
              lastError = error;
              await sleep(calculateBackoff(retryConf, attempt));
              continue;
            }

            return { ok: false, error };
          }

          try {
            const json = (await fetchResponse.json()) as
              | Response<any>
              | {
                  ok: false;
                  error: {
                    message?: string;
                    category?: string;
                    code?: string;
                    details?: Record<string, unknown>;
                  };
                };
            if (!json.ok) {
              const error = new VdlError({
                message: json.error.message ?? "Unknown error",
                category: json.error.category,
                code: json.error.code,
                details: json.error.details,
              });
              const canRetry =
                attempt < retryConf.maxAttempts &&
                (await this.shouldRetry(retryConf, {
                  attempt,
                  maxAttempts: retryConf.maxAttempts,
                  error,
                  input,
                  operation,
                  defaultRetryable: false,
                }));

              if (canRetry) {
                lastError = error;
                await sleep(calculateBackoff(retryConf, attempt));
                continue;
              }

              return { ok: false, error };
            }

            return json;
          } catch (error) {
            const decodeError = new VdlError({
              message: "Failed to decode VDL response: " + String(error),
              category: "ClientError",
              code: "DECODE_RESPONSE",
            });
            const canRetry =
              attempt < retryConf.maxAttempts &&
              (await this.shouldRetry(retryConf, {
                attempt,
                maxAttempts: retryConf.maxAttempts,
                error: decodeError,
                input,
                operation,
                defaultRetryable: false,
              }));

            if (canRetry) {
              lastError = decodeError;
              await sleep(calculateBackoff(retryConf, attempt));
              continue;
            }

            return { ok: false, error: decodeError };
          }
        } catch (error) {
          if (timeoutId !== undefined) {
            clearTimeout(timeoutId);
          }
          opSignal?.removeEventListener("abort", onExternalAbort);

          if (opSignal?.aborted) {
            return {
              ok: false,
              error: new VdlError({
                message: "Request aborted",
                category: "ClientError",
                code: "ABORTED",
              }),
            };
          }

          const normalizedError =
            abortController.signal.aborted && timeoutConf.timeoutMs > 0
              ? new VdlError({
                  message: "Request timeout",
                  category: "TimeoutError",
                  code: "REQUEST_TIMEOUT",
                  details: { attempt },
                })
              : asError(error);

          const canRetry =
            attempt < retryConf.maxAttempts &&
            (await this.shouldRetry(retryConf, {
              attempt,
              maxAttempts: retryConf.maxAttempts,
              error: normalizedError,
              input,
              operation,
              defaultRetryable: true,
            }));

          if (canRetry) {
            lastError = normalizedError;
            await sleep(calculateBackoff(retryConf, attempt));
            continue;
          }

          return { ok: false, error: normalizedError };
        }
      }

      return {
        ok: false,
        error:
          lastError ??
          new VdlError({
            message: "Unknown error",
            category: "ClientError",
            code: "UNKNOWN",
          }),
      };
    };

    return this.executeChain(reqInfo, invoker) as Promise<Response<any>>;
  }

  /**
   * Opens one stream subscription and returns an async event generator plus a cancel handle.
   */
  callStream(
    rpcName: string,
    streamName: string,
    input: unknown,
    opHeaderProviders: HeaderProvider[],
    opReconnectConf?: ReconnectConfig,
    opMaxMessageSize?: number,
    onConnect?: () => void,
    onDisconnect?: (error: Error | null) => void,
    onReconnect?: (attempt: number, delayMs: number) => void,
    opSignal?: AbortSignal,
  ): {
    stream: AsyncGenerator<Response<any>, void, unknown>;
    cancel: () => void;
  } {
    const operation = this.getOperation(rpcName, streamName, "stream");
    const reqInfo: RequestInfo = {
      rpcName,
      operationName: streamName,
      input,
      type: "stream",
      operation,
    };
    const self = this;
    let isCancelled = false;
    let currentAbortController: AbortController | null = null;

    const cancel = () => {
      isCancelled = true;
      currentAbortController?.abort();
    };

    const onExternalAbort = () => {
      isCancelled = true;
      currentAbortController?.abort();
    };

    if (opSignal?.aborted) {
      isCancelled = true;
    }

    async function* generator(): AsyncGenerator<Response<any>, void, unknown> {
      let finalError: VdlError | null = null;
      if (opSignal && !opSignal.aborted) {
        opSignal.addEventListener("abort", onExternalAbort);
      }

      try {
        if (!operation) {
          yield {
            ok: false,
            error: new VdlError({
              message:
                rpcName + "." + streamName + " stream not found in schema",
              category: "ClientError",
              code: "INVALID_STREAM",
              details: { rpc: rpcName, stream: streamName },
            }),
          };
          return;
        }

        let payload: string;
        try {
          payload = input == null ? "{}" : JSON.stringify(input);
        } catch (error) {
          finalError = asError(error);
          yield { ok: false, error: asError(finalError) };
          return;
        }

        const reconnectConf = self.mergeReconnectConfig(
          rpcName,
          opReconnectConf,
        );
        const maxMessageSize = self.mergeMaxMessageSize(
          rpcName,
          opMaxMessageSize,
        );
        const url = self.baseURL + "/" + rpcName + "/" + streamName;
        let reconnectAttempt = 0;

        while (!isCancelled) {
          currentAbortController = new AbortController();

          try {
            const headers: Record<string, string> = {
              "content-type": "application/json",
              accept: "text/event-stream",
            };

            await self.applyHeaders(rpcName, headers, opHeaderProviders);

            const fetchResponse = await self.fetchFn(url, {
              method: "POST",
              headers,
              body: payload,
              signal: currentAbortController.signal,
            });

            if (fetchResponse.status >= 500) {
              const error = new VdlError({
                message:
                  "Unexpected HTTP status: " + String(fetchResponse.status),
                category: "HTTPError",
                code: "BAD_STATUS",
                details: { status: fetchResponse.status },
              });
              const delayMs = calculateReconnectBackoff(
                reconnectConf,
                reconnectAttempt + 1,
              );
              const canReconnect =
                reconnectAttempt < reconnectConf.maxAttempts &&
                (await self.shouldReconnect(reconnectConf, {
                  attempt: reconnectAttempt + 1,
                  maxAttempts: reconnectConf.maxAttempts,
                  error,
                  input,
                  operation,
                  delayMs,
                  defaultReconnectable: true,
                }));

              if (canReconnect) {
                onReconnect?.(reconnectAttempt + 1, delayMs);
                reconnectAttempt += 1;
                await sleep(delayMs);
                continue;
              }

              finalError = error;
              yield { ok: false, error };
              return;
            }

            if (!fetchResponse.ok) {
              const error = new VdlError({
                message:
                  "Unexpected HTTP status: " + String(fetchResponse.status),
                category: "HTTPError",
                code: "BAD_STATUS",
                details: { status: fetchResponse.status },
              });
              const delayMs = calculateReconnectBackoff(
                reconnectConf,
                reconnectAttempt + 1,
              );
              const canReconnect =
                reconnectAttempt < reconnectConf.maxAttempts &&
                (await self.shouldReconnect(reconnectConf, {
                  attempt: reconnectAttempt + 1,
                  maxAttempts: reconnectConf.maxAttempts,
                  error,
                  input,
                  operation,
                  delayMs,
                  defaultReconnectable: false,
                }));

              if (canReconnect) {
                onReconnect?.(reconnectAttempt + 1, delayMs);
                reconnectAttempt += 1;
                await sleep(delayMs);
                continue;
              }

              finalError = error;
              yield { ok: false, error };
              return;
            }

            if (!fetchResponse.body) {
              const error = new VdlError({
                message: "Missing response body for stream",
                category: "ConnectionError",
                code: "STREAM_CONNECT_FAILED",
              });
              finalError = error;
              yield { ok: false, error };
              return;
            }

            onConnect?.();
            reconnectAttempt = 0;

            const reader = fetchResponse.body.getReader();
            const decoder = new TextDecoder();
            let buffer = "";

            try {
              while (!isCancelled) {
                const { done, value } = await reader.read();
                if (done) {
                  break;
                }

                buffer += decoder.decode(value, { stream: true });

                let separatorIndex = buffer.indexOf("\n\n");
                while (separatorIndex >= 0) {
                  const chunk = buffer.slice(0, separatorIndex).trim();
                  buffer = buffer.slice(separatorIndex + 2);

                  if (chunk === "" || chunk.startsWith(":")) {
                    separatorIndex = buffer.indexOf("\n\n");
                    continue;
                  }

                  if (chunk.startsWith("data:")) {
                    const payloadText = chunk.slice(5).trim();
                    if (payloadText.length > maxMessageSize) {
                      finalError = new VdlError({
                        message:
                          "Stream message exceeded maximum size of " +
                          String(maxMessageSize) +
                          " bytes",
                        category: "ProtocolError",
                        code: "MESSAGE_TOO_LARGE",
                      });
                      yield { ok: false, error: asError(finalError) };
                      return;
                    }

                    try {
                      const event = JSON.parse(payloadText) as
                        | Response<any>
                        | {
                            ok: false;
                            error: {
                              message?: string;
                              category?: string;
                              code?: string;
                              details?: Record<string, unknown>;
                            };
                          };
                      if (!event.ok) {
                        yield {
                          ok: false,
                          error: new VdlError({
                            message: event.error.message ?? "Unknown error",
                            category: event.error.category,
                            code: event.error.code,
                            details: event.error.details,
                          }),
                        };
                      } else {
                        yield event;
                      }
                    } catch (error) {
                      finalError = new VdlError({
                        message:
                          "Received invalid SSE payload: " + String(error),
                        category: "ProtocolError",
                        code: "INVALID_PAYLOAD",
                      });
                      yield { ok: false, error: asError(finalError) };
                      return;
                    }
                  }

                  if (buffer.length > maxMessageSize) {
                    finalError = new VdlError({
                      message:
                        "Stream message accumulation exceeded maximum size of " +
                        String(maxMessageSize) +
                        " bytes",
                      category: "ProtocolError",
                      code: "MESSAGE_TOO_LARGE",
                    });
                    yield { ok: false, error: asError(finalError) };
                    return;
                  }

                  separatorIndex = buffer.indexOf("\n\n");
                }
              }

              return;
            } catch (error) {
              const normalizedError = asError(error);
              const delayMs = calculateReconnectBackoff(
                reconnectConf,
                reconnectAttempt + 1,
              );
              const canReconnect =
                !isCancelled &&
                reconnectAttempt < reconnectConf.maxAttempts &&
                (await self.shouldReconnect(reconnectConf, {
                  attempt: reconnectAttempt + 1,
                  maxAttempts: reconnectConf.maxAttempts,
                  error: normalizedError,
                  input,
                  operation,
                  delayMs,
                  defaultReconnectable: true,
                }));

              if (canReconnect) {
                onReconnect?.(reconnectAttempt + 1, delayMs);
                reconnectAttempt += 1;
                await sleep(delayMs);
                continue;
              }

              finalError = normalizedError;
              yield { ok: false, error: normalizedError };
              return;
            }
          } catch (error) {
            const normalizedError = asError(error);
            const delayMs = calculateReconnectBackoff(
              reconnectConf,
              reconnectAttempt + 1,
            );
            const canReconnect =
              !isCancelled &&
              reconnectAttempt < reconnectConf.maxAttempts &&
              (await self.shouldReconnect(reconnectConf, {
                attempt: reconnectAttempt + 1,
                maxAttempts: reconnectConf.maxAttempts,
                error: normalizedError,
                input,
                operation,
                delayMs,
                defaultReconnectable: true,
              }));

            if (canReconnect) {
              onReconnect?.(reconnectAttempt + 1, delayMs);
              reconnectAttempt += 1;
              await sleep(delayMs);
              continue;
            }

            finalError = normalizedError;
            if (!isCancelled) {
              yield { ok: false, error: normalizedError };
            }
            return;
          }
        }
      } finally {
        opSignal?.removeEventListener("abort", onExternalAbort);
        onDisconnect?.(finalError);
      }
    }

    const wrappedGenerator = async function* () {
      const result = await self.executeChain(reqInfo, async () => ({
        ok: true,
        output: null,
      }));
      if (!result.ok) {
        yield result;
        return;
      }
      yield* generator();
    };

    return {
      stream: wrappedGenerator(),
      cancel,
    };
  }
}

/**
 * Internal mutator applied while building an internalClient instance.
 */
type internalClientOption = (client: internalClient) => void;

/** Creates an option that replaces the fetch implementation. */
function withFetch(fetchFn: FetchLike): internalClientOption {
  return (client) => client.setFetch(fetchFn);
}

/** Creates an option that appends one static global header provider. */
function withGlobalHeader(key: string, value: string): internalClientOption {
  return (client) =>
    client.addHeaderProvider((headers) => {
      headers[key] = value;
    });
}

/** Creates an option that appends one dynamic global header provider. */
function withHeaderProvider(provider: HeaderProvider): internalClientOption {
  return (client) => client.addHeaderProvider(provider);
}

/** Creates an option that appends one interceptor. */
function withInterceptor(interceptor: Interceptor): internalClientOption {
  return (client) => client.addInterceptor(interceptor);
}

/** Creates an option that sets the global retry policy. */
function withGlobalRetryConfig(conf: RetryConfig): internalClientOption {
  return (client) => client.setGlobalRetryConfig(conf);
}

/** Creates an option that sets the global timeout policy. */
function withGlobalTimeoutConfig(conf: TimeoutConfig): internalClientOption {
  return (client) => client.setGlobalTimeoutConfig(conf);
}

/** Creates an option that sets the global reconnect policy. */
function withGlobalReconnectConfig(
  conf: ReconnectConfig,
): internalClientOption {
  return (client) => client.setGlobalReconnectConfig(conf);
}

/** Creates an option that sets the global maximum stream message size. */
function withGlobalMaxMessageSize(size: number): internalClientOption {
  return (client) => client.setGlobalMaxMessageSize(size);
}

/**
 * Fluent builder for constructing an internalClient with layered defaults.
 */
class clientBuilder {
  private readonly baseURL: string;
  private readonly procDefs: OperationDefinition[];
  private readonly streamDefs: OperationDefinition[];
  private readonly opts: internalClientOption[] = [];

  /** Creates a new builder bound to the generated operation catalogs. */
  constructor(
    baseURL: string,
    procDefs: OperationDefinition[],
    streamDefs: OperationDefinition[],
  ) {
    this.baseURL = baseURL;
    this.procDefs = procDefs;
    this.streamDefs = streamDefs;
  }

  /** Overrides the fetch implementation used by the internal client. */
  withFetch(fetchFn: FetchLike): clientBuilder {
    this.opts.push(withFetch(fetchFn));
    return this;
  }

  /** Appends one static global header provider. */
  withGlobalHeader(key: string, value: string): clientBuilder {
    this.opts.push(withGlobalHeader(key, value));
    return this;
  }

  /** Appends one dynamic global header provider. */
  withHeaderProvider(provider: HeaderProvider): clientBuilder {
    this.opts.push(withHeaderProvider(provider));
    return this;
  }

  /** Appends one interceptor to the global chain. */
  withInterceptor(interceptor: Interceptor): clientBuilder {
    this.opts.push(withInterceptor(interceptor));
    return this;
  }

  /** Sets the global retry policy default. */
  withGlobalRetryConfig(conf: RetryConfig): clientBuilder {
    this.opts.push(withGlobalRetryConfig(conf));
    return this;
  }

  /** Sets the global timeout policy default. */
  withGlobalTimeoutConfig(conf: TimeoutConfig): clientBuilder {
    this.opts.push(withGlobalTimeoutConfig(conf));
    return this;
  }

  /** Sets the global reconnect policy default. */
  withGlobalReconnectConfig(conf: ReconnectConfig): clientBuilder {
    this.opts.push(withGlobalReconnectConfig(conf));
    return this;
  }

  /** Sets the global maximum stream message size default. */
  withGlobalMaxMessageSize(size: number): clientBuilder {
    this.opts.push(withGlobalMaxMessageSize(size));
    return this;
  }

  /** Builds the final internal client instance. */
  build(): internalClient {
    return new internalClient(
      this.baseURL,
      this.procDefs,
      this.streamDefs,
      this.opts,
    );
  }
}
/**
 * Creates a new VDL RPC client builder.
 */
export function NewClient(baseURL: string): ClientBuilder {
  return new ClientBuilder(baseURL);
}

/**
 * Fluent builder for configuring a generated RPC client.
 */
export class ClientBuilder {
  private readonly builder: clientBuilder;

  constructor(baseURL: string) {
    this.builder = new clientBuilder(baseURL, VDLProcedures, VDLStreams);
  }

  /**
   * Sets a custom fetch implementation for the generated client.
   */
  withCustomFetch(fetchFn: FetchLike): ClientBuilder {
    this.builder.withFetch(fetchFn);
    return this;
  }

  /**
   * Adds a static header that will be sent with every request.
   */
  withGlobalHeader(key: string, value: string): ClientBuilder {
    this.builder.withGlobalHeader(key, value);
    return this;
  }

  /**
   * Adds a dynamic header provider that runs before every request attempt.
   */
  withHeaderProvider(provider: HeaderProvider): ClientBuilder {
    this.builder.withHeaderProvider(provider);
    return this;
  }

  /**
   * Adds an interceptor around generated client execution.
   */
  withInterceptor(interceptor: Interceptor): ClientBuilder {
    this.builder.withInterceptor(interceptor);
    return this;
  }

  /**
   * Sets the global default retry policy for generated procedures.
   */
  withGlobalRetryConfig(conf: RetryConfig): ClientBuilder {
    this.builder.withGlobalRetryConfig(conf);
    return this;
  }

  /**
   * Sets the global default timeout for generated procedures.
   */
  withGlobalTimeoutConfig(conf: TimeoutConfig): ClientBuilder {
    this.builder.withGlobalTimeoutConfig(conf);
    return this;
  }

  /**
   * Sets the global default reconnect policy for generated streams.
   */
  withGlobalReconnectConfig(conf: ReconnectConfig): ClientBuilder {
    this.builder.withGlobalReconnectConfig(conf);
    return this;
  }

  /**
   * Sets the global maximum stream message size.
   */
  withGlobalMaxMessageSize(size: number): ClientBuilder {
    this.builder.withGlobalMaxMessageSize(size);
    return this;
  }

  /**
   * Builds the configured client instance.
   */
  build(): Client {
    return new Client(this.builder.build());
  }
}

/**
 * Main VDL RPC client exposing typed access to generated procedures and streams.
 */
export class Client {
  private readonly intClient: internalClient;
  public readonly rpcs: ClientRPCRegistry;
  public readonly procs: ProcRegistry;
  public readonly streams: StreamRegistry;

  constructor(intClient: internalClient) {
    this.intClient = intClient;
    this.rpcs = new ClientRPCRegistry(intClient);
    this.procs = new ProcRegistry(intClient);
    this.streams = new StreamRegistry(intClient);
  }
}

/**
 * Registry exposing every generated RPC service.
 */
class ClientRPCRegistry {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

  /**
   * Access the Database RPC service.
   */
  database(): ClientDatabaseRPC { return new ClientDatabaseRPC(this.intClient); }

  /**
   * Access the System RPC service.
   */
  system(): ClientSystemRPC { return new ClientSystemRPC(this.intClient); }

}

/**
 * Client-side access point for the Database RPC service and its defaults.
 */
class ClientDatabaseRPC {
  private readonly intClient: internalClient;
  public readonly procs: ClientDatabaseProcs;
  public readonly streams: ClientDatabaseStreams;

  constructor(intClient: internalClient) {
    this.intClient = intClient;
    this.procs = new ClientDatabaseProcs(intClient);
    this.streams = new ClientDatabaseStreams(intClient);
  }

  /**
   * Adds a static default header for every Database request.
   */
  withHeader(key: string, value: string): ClientDatabaseRPC {
    this.intClient.setRPCHeaderProvider("Database", (headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic default header provider for every Database request.
   */
  withHeaderProvider(provider: HeaderProvider): ClientDatabaseRPC {
    this.intClient.setRPCHeaderProvider("Database", provider);
    return this;
  }

  /**
   * Sets the default retry policy for procedures in Database.
   */
  withRetries(config: Partial<RetryConfig>): ClientDatabaseRPC {
    this.intClient.setRPCRetryConfig("Database", normalizeRetryConfig(config, 3));
    return this;
  }

  /**
   * Sets the exact retry configuration for procedures in Database.
   */
  withRetryConfig(config: RetryConfig): ClientDatabaseRPC {
    this.intClient.setRPCRetryConfig("Database", normalizeRetryConfig(config, config.maxAttempts));
    return this;
  }

  /**
   * Sets the default timeout policy for procedures in Database.
   */
  withTimeout(config: Partial<TimeoutConfig>): ClientDatabaseRPC {
    this.intClient.setRPCTimeoutConfig("Database", normalizeTimeoutConfig(config));
    return this;
  }

  /**
   * Sets the exact timeout configuration for procedures in Database.
   */
  withTimeoutConfig(config: TimeoutConfig): ClientDatabaseRPC {
    this.intClient.setRPCTimeoutConfig("Database", normalizeTimeoutConfig(config));
    return this;
  }

  /**
   * Sets the default reconnect policy for streams in Database.
   */
  withReconnect(config: Partial<ReconnectConfig>): ClientDatabaseRPC {
    this.intClient.setRPCReconnectConfig("Database", normalizeReconnectConfig(config, 5));
    return this;
  }

  /**
   * Sets the exact reconnect configuration for streams in Database.
   */
  withReconnectConfig(config: ReconnectConfig): ClientDatabaseRPC {
    this.intClient.setRPCReconnectConfig("Database", normalizeReconnectConfig(config, config.maxAttempts));
    return this;
  }

  /**
   * Sets the default maximum stream message size for Database.
   */
  withMaxMessageSize(size: number): ClientDatabaseRPC {
    this.intClient.setRPCMaxMessageSize("Database", size);
    return this;
  }
}

/**
 * Registry exposing every generated procedure builder for Database.
 */
class ClientDatabaseProcs {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

  /**
   * Executes one or more SQL queries against the database.
   *
   * Queries are executed in order and each query returns one result item.
   * Empty or failed queries are returned as result items with type "error".
   */
  query(): ProcDatabasequeryBuilder { return new ProcDatabasequeryBuilder(this.intClient, "Database", "query"); }

}

/**
 * Registry exposing every generated stream builder for Database.
 */
class ClientDatabaseStreams {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

}

/**
 * Client-side access point for the System RPC service and its defaults.
 */
class ClientSystemRPC {
  private readonly intClient: internalClient;
  public readonly procs: ClientSystemProcs;
  public readonly streams: ClientSystemStreams;

  constructor(intClient: internalClient) {
    this.intClient = intClient;
    this.procs = new ClientSystemProcs(intClient);
    this.streams = new ClientSystemStreams(intClient);
  }

  /**
   * Adds a static default header for every System request.
   */
  withHeader(key: string, value: string): ClientSystemRPC {
    this.intClient.setRPCHeaderProvider("System", (headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic default header provider for every System request.
   */
  withHeaderProvider(provider: HeaderProvider): ClientSystemRPC {
    this.intClient.setRPCHeaderProvider("System", provider);
    return this;
  }

  /**
   * Sets the default retry policy for procedures in System.
   */
  withRetries(config: Partial<RetryConfig>): ClientSystemRPC {
    this.intClient.setRPCRetryConfig("System", normalizeRetryConfig(config, 3));
    return this;
  }

  /**
   * Sets the exact retry configuration for procedures in System.
   */
  withRetryConfig(config: RetryConfig): ClientSystemRPC {
    this.intClient.setRPCRetryConfig("System", normalizeRetryConfig(config, config.maxAttempts));
    return this;
  }

  /**
   * Sets the default timeout policy for procedures in System.
   */
  withTimeout(config: Partial<TimeoutConfig>): ClientSystemRPC {
    this.intClient.setRPCTimeoutConfig("System", normalizeTimeoutConfig(config));
    return this;
  }

  /**
   * Sets the exact timeout configuration for procedures in System.
   */
  withTimeoutConfig(config: TimeoutConfig): ClientSystemRPC {
    this.intClient.setRPCTimeoutConfig("System", normalizeTimeoutConfig(config));
    return this;
  }

  /**
   * Sets the default reconnect policy for streams in System.
   */
  withReconnect(config: Partial<ReconnectConfig>): ClientSystemRPC {
    this.intClient.setRPCReconnectConfig("System", normalizeReconnectConfig(config, 5));
    return this;
  }

  /**
   * Sets the exact reconnect configuration for streams in System.
   */
  withReconnectConfig(config: ReconnectConfig): ClientSystemRPC {
    this.intClient.setRPCReconnectConfig("System", normalizeReconnectConfig(config, config.maxAttempts));
    return this;
  }

  /**
   * Sets the default maximum stream message size for System.
   */
  withMaxMessageSize(size: number): ClientSystemRPC {
    this.intClient.setRPCMaxMessageSize("System", size);
    return this;
  }
}

/**
 * Registry exposing every generated procedure builder for System.
 */
class ClientSystemProcs {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

  /**
   * Checks whether the server can perform a basic database read.
   */
  health(): ProcSystemhealthBuilder { return new ProcSystemhealthBuilder(this.intClient, "System", "health"); }

  /**
   * Returns the authentication role for the current session.
   */
  session(): ProcSystemsessionBuilder { return new ProcSystemsessionBuilder(this.intClient, "System", "session"); }

  /**
   * Returns server information and runtime statistics.
   */
  status(): ProcSystemstatusBuilder { return new ProcSystemstatusBuilder(this.intClient, "System", "status"); }

}

/**
 * Registry exposing every generated stream builder for System.
 */
class ClientSystemStreams {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

}

/**
 * Registry exposing every generated procedure builder.
 */
class ProcRegistry {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

  /**
   * Executes one or more SQL queries against the database.
   *
   * Queries are executed in order and each query returns one result item.
   * Empty or failed queries are returned as result items with type "error".
   */
  databaseQuery(): ProcDatabasequeryBuilder { return new ProcDatabasequeryBuilder(this.intClient, "Database", "query"); }

  /**
   * Checks whether the server can perform a basic database read.
   */
  systemHealth(): ProcSystemhealthBuilder { return new ProcSystemhealthBuilder(this.intClient, "System", "health"); }

  /**
   * Returns the authentication role for the current session.
   */
  systemSession(): ProcSystemsessionBuilder { return new ProcSystemsessionBuilder(this.intClient, "System", "session"); }

  /**
   * Returns server information and runtime statistics.
   */
  systemStatus(): ProcSystemstatusBuilder { return new ProcSystemstatusBuilder(this.intClient, "System", "status"); }

}

class ProcDatabasequeryBuilder {
  private readonly intClient: internalClient;
  private readonly rpcName: string;
  private readonly procName: string;
  private readonly headerProviders: HeaderProvider[] = [];
  private retryConfig?: RetryConfig;
  private timeoutConfig?: TimeoutConfig;
  private signal?: AbortSignal;

  constructor(intClient: internalClient, rpcName: string, procName: string) {
    this.intClient = intClient;
    this.rpcName = rpcName;
    this.procName = procName;
  }

  /**
   * Adds a static header to this procedure call.
   */
  withHeader(key: string, value: string): ProcDatabasequeryBuilder {
    this.headerProviders.push((headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic header provider to this procedure call. The provider runs on every attempt, including retries.
   */
  withHeaderProvider(provider: HeaderProvider): ProcDatabasequeryBuilder {
    this.headerProviders.push(provider);
    return this;
  }

  /**
   * Configures retry behavior for this procedure call. The optional shouldRetry callback receives the resolved operation metadata, including annotations.
   */
  withRetries(config: Partial<RetryConfig>): ProcDatabasequeryBuilder {
    this.retryConfig = normalizeRetryConfig(config, 3);
    return this;
  }

  /**
   * Sets the exact retry configuration for this procedure call, including max attempts.
   */
  withRetryConfig(config: RetryConfig): ProcDatabasequeryBuilder {
    this.retryConfig = normalizeRetryConfig(config, config.maxAttempts);
    return this;
  }

  /**
   * Configures timeout behavior for this procedure call.
   */
  withTimeout(config: Partial<TimeoutConfig>): ProcDatabasequeryBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets the exact timeout configuration for this procedure call.
   */
  withTimeoutConfig(config: TimeoutConfig): ProcDatabasequeryBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets an external AbortSignal used to cancel this procedure call.
   */
  withSignal(signal: AbortSignal): ProcDatabasequeryBuilder {
    this.signal = signal;
    return this;
  }

  /**
   * Executes one or more SQL queries against the database.
   *
   * Queries are executed in order and each query returns one result item.
   * Empty or failed queries are returned as result items with type "error".
   */
  async execute(input: vdlTypes.DatabaseQueryInput): Promise<vdlTypes.DatabaseQueryOutput> {
    const validationError = vdlTypes.DatabaseQueryInput.validate(input);
    if (validationError !== null) {
      throw new VdlError({ message: validationError, code: "INVALID_INPUT", category: "ValidationError" });
    }
    const rawResponse = await this.intClient.callProc(this.rpcName, this.procName, input, this.headerProviders, this.retryConfig, this.timeoutConfig, this.signal);
    if (!rawResponse.ok) {
      throw rawResponse.error;
    }
    return vdlTypes.DatabaseQueryOutput.hydrate(rawResponse.output as vdlTypes.DatabaseQueryOutput);
  }
}

class ProcSystemhealthBuilder {
  private readonly intClient: internalClient;
  private readonly rpcName: string;
  private readonly procName: string;
  private readonly headerProviders: HeaderProvider[] = [];
  private retryConfig?: RetryConfig;
  private timeoutConfig?: TimeoutConfig;
  private signal?: AbortSignal;

  constructor(intClient: internalClient, rpcName: string, procName: string) {
    this.intClient = intClient;
    this.rpcName = rpcName;
    this.procName = procName;
  }

  /**
   * Adds a static header to this procedure call.
   */
  withHeader(key: string, value: string): ProcSystemhealthBuilder {
    this.headerProviders.push((headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic header provider to this procedure call. The provider runs on every attempt, including retries.
   */
  withHeaderProvider(provider: HeaderProvider): ProcSystemhealthBuilder {
    this.headerProviders.push(provider);
    return this;
  }

  /**
   * Configures retry behavior for this procedure call. The optional shouldRetry callback receives the resolved operation metadata, including annotations.
   */
  withRetries(config: Partial<RetryConfig>): ProcSystemhealthBuilder {
    this.retryConfig = normalizeRetryConfig(config, 3);
    return this;
  }

  /**
   * Sets the exact retry configuration for this procedure call, including max attempts.
   */
  withRetryConfig(config: RetryConfig): ProcSystemhealthBuilder {
    this.retryConfig = normalizeRetryConfig(config, config.maxAttempts);
    return this;
  }

  /**
   * Configures timeout behavior for this procedure call.
   */
  withTimeout(config: Partial<TimeoutConfig>): ProcSystemhealthBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets the exact timeout configuration for this procedure call.
   */
  withTimeoutConfig(config: TimeoutConfig): ProcSystemhealthBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets an external AbortSignal used to cancel this procedure call.
   */
  withSignal(signal: AbortSignal): ProcSystemhealthBuilder {
    this.signal = signal;
    return this;
  }

  /**
   * Checks whether the server can perform a basic database read.
   */
  async execute(input: Void = {}): Promise<vdlTypes.SystemHealthOutput> {
    const validationError = Void.validate(input);
    if (validationError !== null) {
      throw new VdlError({ message: validationError, code: "INVALID_INPUT", category: "ValidationError" });
    }
    const rawResponse = await this.intClient.callProc(this.rpcName, this.procName, input, this.headerProviders, this.retryConfig, this.timeoutConfig, this.signal);
    if (!rawResponse.ok) {
      throw rawResponse.error;
    }
    return vdlTypes.SystemHealthOutput.hydrate(rawResponse.output as vdlTypes.SystemHealthOutput);
  }
}

class ProcSystemsessionBuilder {
  private readonly intClient: internalClient;
  private readonly rpcName: string;
  private readonly procName: string;
  private readonly headerProviders: HeaderProvider[] = [];
  private retryConfig?: RetryConfig;
  private timeoutConfig?: TimeoutConfig;
  private signal?: AbortSignal;

  constructor(intClient: internalClient, rpcName: string, procName: string) {
    this.intClient = intClient;
    this.rpcName = rpcName;
    this.procName = procName;
  }

  /**
   * Adds a static header to this procedure call.
   */
  withHeader(key: string, value: string): ProcSystemsessionBuilder {
    this.headerProviders.push((headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic header provider to this procedure call. The provider runs on every attempt, including retries.
   */
  withHeaderProvider(provider: HeaderProvider): ProcSystemsessionBuilder {
    this.headerProviders.push(provider);
    return this;
  }

  /**
   * Configures retry behavior for this procedure call. The optional shouldRetry callback receives the resolved operation metadata, including annotations.
   */
  withRetries(config: Partial<RetryConfig>): ProcSystemsessionBuilder {
    this.retryConfig = normalizeRetryConfig(config, 3);
    return this;
  }

  /**
   * Sets the exact retry configuration for this procedure call, including max attempts.
   */
  withRetryConfig(config: RetryConfig): ProcSystemsessionBuilder {
    this.retryConfig = normalizeRetryConfig(config, config.maxAttempts);
    return this;
  }

  /**
   * Configures timeout behavior for this procedure call.
   */
  withTimeout(config: Partial<TimeoutConfig>): ProcSystemsessionBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets the exact timeout configuration for this procedure call.
   */
  withTimeoutConfig(config: TimeoutConfig): ProcSystemsessionBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets an external AbortSignal used to cancel this procedure call.
   */
  withSignal(signal: AbortSignal): ProcSystemsessionBuilder {
    this.signal = signal;
    return this;
  }

  /**
   * Returns the authentication role for the current session.
   */
  async execute(input: Void = {}): Promise<vdlTypes.SystemSessionOutput> {
    const validationError = Void.validate(input);
    if (validationError !== null) {
      throw new VdlError({ message: validationError, code: "INVALID_INPUT", category: "ValidationError" });
    }
    const rawResponse = await this.intClient.callProc(this.rpcName, this.procName, input, this.headerProviders, this.retryConfig, this.timeoutConfig, this.signal);
    if (!rawResponse.ok) {
      throw rawResponse.error;
    }
    return vdlTypes.SystemSessionOutput.hydrate(rawResponse.output as vdlTypes.SystemSessionOutput);
  }
}

class ProcSystemstatusBuilder {
  private readonly intClient: internalClient;
  private readonly rpcName: string;
  private readonly procName: string;
  private readonly headerProviders: HeaderProvider[] = [];
  private retryConfig?: RetryConfig;
  private timeoutConfig?: TimeoutConfig;
  private signal?: AbortSignal;

  constructor(intClient: internalClient, rpcName: string, procName: string) {
    this.intClient = intClient;
    this.rpcName = rpcName;
    this.procName = procName;
  }

  /**
   * Adds a static header to this procedure call.
   */
  withHeader(key: string, value: string): ProcSystemstatusBuilder {
    this.headerProviders.push((headers) => { headers[key] = value; });
    return this;
  }

  /**
   * Adds a dynamic header provider to this procedure call. The provider runs on every attempt, including retries.
   */
  withHeaderProvider(provider: HeaderProvider): ProcSystemstatusBuilder {
    this.headerProviders.push(provider);
    return this;
  }

  /**
   * Configures retry behavior for this procedure call. The optional shouldRetry callback receives the resolved operation metadata, including annotations.
   */
  withRetries(config: Partial<RetryConfig>): ProcSystemstatusBuilder {
    this.retryConfig = normalizeRetryConfig(config, 3);
    return this;
  }

  /**
   * Sets the exact retry configuration for this procedure call, including max attempts.
   */
  withRetryConfig(config: RetryConfig): ProcSystemstatusBuilder {
    this.retryConfig = normalizeRetryConfig(config, config.maxAttempts);
    return this;
  }

  /**
   * Configures timeout behavior for this procedure call.
   */
  withTimeout(config: Partial<TimeoutConfig>): ProcSystemstatusBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets the exact timeout configuration for this procedure call.
   */
  withTimeoutConfig(config: TimeoutConfig): ProcSystemstatusBuilder {
    this.timeoutConfig = normalizeTimeoutConfig(config);
    return this;
  }

  /**
   * Sets an external AbortSignal used to cancel this procedure call.
   */
  withSignal(signal: AbortSignal): ProcSystemstatusBuilder {
    this.signal = signal;
    return this;
  }

  /**
   * Returns server information and runtime statistics.
   */
  async execute(input: Void = {}): Promise<vdlTypes.SystemStatusOutput> {
    const validationError = Void.validate(input);
    if (validationError !== null) {
      throw new VdlError({ message: validationError, code: "INVALID_INPUT", category: "ValidationError" });
    }
    const rawResponse = await this.intClient.callProc(this.rpcName, this.procName, input, this.headerProviders, this.retryConfig, this.timeoutConfig, this.signal);
    if (!rawResponse.ok) {
      throw rawResponse.error;
    }
    return vdlTypes.SystemStatusOutput.hydrate(rawResponse.output as vdlTypes.SystemStatusOutput);
  }
}

/**
 * Registry exposing every generated stream builder.
 */
class StreamRegistry {
  private readonly intClient: internalClient;
  constructor(intClient: internalClient) {
    this.intClient = intClient;
  }

}
