// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-ts@v0.1.4 (hash a17e7e58)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

/**
 * AuthRole declares a generated VDL enum.
 */
export type AuthRole = "admin" | "rw" | "ro";

/**
 * AuthRole exposes the generated enum values and runtime helpers for AuthRole.
 */
export const AuthRole = {
  /**
   * Full administrative access.
   */
  Admin: "admin" as AuthRole,

  /**
   * Read and write access to the database.
   */
  ReadWrite: "rw" as AuthRole,

  /**
   * Read-only access to the database.
   */
  ReadOnly: "ro" as AuthRole,

  /**
   * Returns every declared AuthRole value in definition order.
   */
  values(): AuthRole[] {
    return ["admin", "rw", "ro"];
  },

  /**
   * Parses a JSON string into a validated and hydrated AuthRole value.
   */
  parse(json: string): AuthRole {
    const input = _vdl.parseJson(json);
    const error = AuthRole.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return AuthRole.hydrate(input as AuthRole);
  },

  /**
   * Performs structural enum validation only (membership in AuthRole); it does not enforce business rules.
   */
  validate(input: unknown, path = "AuthRole"): string | null {
    if (!_vdl.arrayIncludes(AuthRole.values(), input)) {
      return `${path}: invalid value "${String(input)}" for AuthRole enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated AuthRole value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: AuthRole): AuthRole {
    return input;
  },
} as const;

/**
 * QueryResultType declares a generated VDL enum.
 */
export type QueryResultType =
  | "read"
  | "write"
  | "begin"
  | "commit"
  | "rollback"
  | "error";

/**
 * QueryResultType exposes the generated enum values and runtime helpers for QueryResultType.
 */
export const QueryResultType = {
  /**
   * A read-only query (SELECT).
   */
  Read: "read" as QueryResultType,

  /**
   * A write query (INSERT, UPDATE, DELETE, CREATE, etc.).
   */
  Write: "write" as QueryResultType,

  /**
   * A BEGIN TRANSACTION query.
   */
  Begin: "begin" as QueryResultType,

  /**
   * A COMMIT TRANSACTION query.
   */
  Commit: "commit" as QueryResultType,

  /**
   * A ROLLBACK TRANSACTION query.
   */
  Rollback: "rollback" as QueryResultType,

  /**
   * An error result produced by an empty or failed query.
   */
  Error: "error" as QueryResultType,

  /**
   * Returns every declared QueryResultType value in definition order.
   */
  values(): QueryResultType[] {
    return ["read", "write", "begin", "commit", "rollback", "error"];
  },

  /**
   * Parses a JSON string into a validated and hydrated QueryResultType value.
   */
  parse(json: string): QueryResultType {
    const input = _vdl.parseJson(json);
    const error = QueryResultType.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return QueryResultType.hydrate(input as QueryResultType);
  },

  /**
   * Performs structural enum validation only (membership in QueryResultType); it does not enforce business rules.
   */
  validate(input: unknown, path = "QueryResultType"): string | null {
    if (!_vdl.arrayIncludes(QueryResultType.values(), input)) {
      return `${path}: invalid value "${String(input)}" for QueryResultType enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated QueryResultType value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: QueryResultType): QueryResultType {
    return input;
  },
} as const;

/**
 * SqliteStorageClass declares a generated VDL enum.
 */
export type SqliteStorageClass = "NULL" | "INTEGER" | "REAL" | "TEXT" | "BLOB";

/**
 * SqliteStorageClass exposes the generated enum values and runtime helpers for SqliteStorageClass.
 */
export const SqliteStorageClass = {
  /**
   * The SQL NULL value.
   */
  Null: "NULL" as SqliteStorageClass,

  /**
   * A signed integer.
   */
  Integer: "INTEGER" as SqliteStorageClass,

  /**
   * A floating-point value.
   */
  Real: "REAL" as SqliteStorageClass,

  /**
   * A text string.
   */
  Text: "TEXT" as SqliteStorageClass,

  /**
   * A binary blob.
   */
  Blob: "BLOB" as SqliteStorageClass,

  /**
   * Returns every declared SqliteStorageClass value in definition order.
   */
  values(): SqliteStorageClass[] {
    return ["NULL", "INTEGER", "REAL", "TEXT", "BLOB"];
  },

  /**
   * Parses a JSON string into a validated and hydrated SqliteStorageClass value.
   */
  parse(json: string): SqliteStorageClass {
    const input = _vdl.parseJson(json);
    const error = SqliteStorageClass.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SqliteStorageClass.hydrate(input as SqliteStorageClass);
  },

  /**
   * Performs structural enum validation only (membership in SqliteStorageClass); it does not enforce business rules.
   */
  validate(input: unknown, path = "SqliteStorageClass"): string | null {
    if (!_vdl.arrayIncludes(SqliteStorageClass.values(), input)) {
      return `${path}: invalid value "${String(input)}" for SqliteStorageClass enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated SqliteStorageClass value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: SqliteStorageClass): SqliteStorageClass {
    return input;
  },
} as const;

/**
 * Internal helpers shared by the generated enum namespaces in this file.
 */
const _vdl = {
  /**
   * Parses JSON text and wraps syntax failures in a stable generated error message.
   */
  parseJson(json: string): unknown {
    try {
      return JSON.parse(json);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Invalid JSON input: ${message}`);
    }
  },

  /**
   * Checks whether an array contains a value using strict equality.
   */
  arrayIncludes<TValue>(values: TValue[], value: unknown): value is TValue {
    for (let index = 0; index < values.length; index += 1) {
      if (values[index] === value) {
        return true;
      }
    }
    return false;
  },
} as const;
