// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-ts@v0.1.4 (hash a17e7e58)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

import { AuthRole, QueryResultType, SqliteStorageClass } from "./enums.ts";

/**
 * Database represents a generated VDL object.
 */
export type Database = {
  /**
   * Executes one or more SQL queries against the database.
   *
   * Queries are executed in order and each query returns one result item.
   * Empty or failed queries are returned as result items with type "error".
   */
  query: DatabaseQuery;
};

/**
 * Database exposes the generated runtime helpers for Database.
 */
export const Database = {
  /**
   * Parses a JSON string into a validated and hydrated Database value.
   */
  parse(json: string): Database {
    const input = _vdl.parseJson(json);
    const error = Database.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Database.hydrate(input as Database);
  },

  /**
   * Performs structural validation for Database (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Database"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.query`;
    if (!_vdl.hasOwn(record0, "query") || record0["query"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = DatabaseQuery.validate(record0["query"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated Database value into its runtime representation.
   */
  hydrate(input: Database): Database {
    return {
      query: DatabaseQuery.hydrate(input.query),
    };
  },
} as const;

/**
 * DatabaseQuery represents a generated VDL object.
 */
export type DatabaseQuery = {
  input: DatabaseQueryInput;
  output: DatabaseQueryOutput;
};

/**
 * DatabaseQuery exposes the generated runtime helpers for DatabaseQuery.
 */
export const DatabaseQuery = {
  /**
   * Parses a JSON string into a validated and hydrated DatabaseQuery value.
   */
  parse(json: string): DatabaseQuery {
    const input = _vdl.parseJson(json);
    const error = DatabaseQuery.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return DatabaseQuery.hydrate(input as DatabaseQuery);
  },

  /**
   * Performs structural validation for DatabaseQuery (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "DatabaseQuery"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.input`;
    if (!_vdl.hasOwn(record0, "input") || record0["input"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = DatabaseQueryInput.validate(record0["input"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.output`;
    if (!_vdl.hasOwn(record0, "output") || record0["output"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    {
      const error = DatabaseQueryOutput.validate(
        record0["output"],
        fieldPath0_1,
      );
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated DatabaseQuery value into its runtime representation.
   */
  hydrate(input: DatabaseQuery): DatabaseQuery {
    return {
      input: DatabaseQueryInput.hydrate(input.input),
      output: DatabaseQueryOutput.hydrate(input.output),
    };
  },
} as const;

/**
 * DatabaseQueryInput represents a generated VDL object.
 */
export type DatabaseQueryInput = {
  /**
   * The list of SQL queries to execute in order.
   */
  queries: Query[];
};

/**
 * DatabaseQueryInput exposes the generated runtime helpers for DatabaseQueryInput.
 */
export const DatabaseQueryInput = {
  /**
   * Parses a JSON string into a validated and hydrated DatabaseQueryInput value.
   */
  parse(json: string): DatabaseQueryInput {
    const input = _vdl.parseJson(json);
    const error = DatabaseQueryInput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return DatabaseQueryInput.hydrate(input as DatabaseQueryInput);
  },

  /**
   * Performs structural validation for DatabaseQueryInput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "DatabaseQueryInput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.queries`;
    if (!_vdl.hasOwn(record0, "queries") || record0["queries"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (!Array.isArray(record0["queries"])) {
      return `${fieldPath0_0}: expected array, got ${_vdl.describeValue(record0["queries"])}`;
    }
    for (let index1 = 0; index1 < record0["queries"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_0}[${index1}]`;
      {
        const error = Query.validate(record0["queries"][index1], itemPath1);
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated DatabaseQueryInput value into its runtime representation.
   */
  hydrate(input: DatabaseQueryInput): DatabaseQueryInput {
    return {
      queries: input.queries.map((item1) => Query.hydrate(item1)),
    };
  },
} as const;

/**
 * DatabaseQueryOutput represents a generated VDL object.
 */
export type DatabaseQueryOutput = {
  /**
   * Total execution time in seconds for all queries.
   */
  time: number;
  /**
   * One result per input query, in the same order.
   */
  results: QueryResult[];
};

/**
 * DatabaseQueryOutput exposes the generated runtime helpers for DatabaseQueryOutput.
 */
export const DatabaseQueryOutput = {
  /**
   * Parses a JSON string into a validated and hydrated DatabaseQueryOutput value.
   */
  parse(json: string): DatabaseQueryOutput {
    const input = _vdl.parseJson(json);
    const error = DatabaseQueryOutput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return DatabaseQueryOutput.hydrate(input as DatabaseQueryOutput);
  },

  /**
   * Performs structural validation for DatabaseQueryOutput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "DatabaseQueryOutput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.time`;
    if (!_vdl.hasOwn(record0, "time") || record0["time"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (
      typeof record0["time"] !== "number" ||
      !Number.isFinite(record0["time"])
    ) {
      return `${fieldPath0_0}: expected number, got ${_vdl.describeValue(record0["time"])}`;
    }
    const fieldPath0_1 = `${path}.results`;
    if (!_vdl.hasOwn(record0, "results") || record0["results"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (!Array.isArray(record0["results"])) {
      return `${fieldPath0_1}: expected array, got ${_vdl.describeValue(record0["results"])}`;
    }
    for (let index1 = 0; index1 < record0["results"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_1}[${index1}]`;
      {
        const error = QueryResult.validate(
          record0["results"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated DatabaseQueryOutput value into its runtime representation.
   */
  hydrate(input: DatabaseQueryOutput): DatabaseQueryOutput {
    return {
      time: input.time,
      results: input.results.map((item1) => QueryResult.hydrate(item1)),
    };
  },
} as const;

/**
 * Query represents a generated VDL object.
 */
export type Query = {
  /**
   * Transaction ID to execute the query within an existing transaction.
   */
  txId?: string;
  /**
   * The SQL query string.
   */
  query: string;
  /**
   * Optional query parameters.
   */
  params?: QueryParam[];
};

/**
 * Query exposes the generated runtime helpers for Query.
 */
export const Query = {
  /**
   * Parses a JSON string into a validated and hydrated Query value.
   */
  parse(json: string): Query {
    const input = _vdl.parseJson(json);
    const error = Query.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Query.hydrate(input as Query);
  },

  /**
   * Performs structural validation for Query (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Query"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.txId`;
    if (_vdl.hasOwn(record0, "txId") && record0["txId"] !== undefined) {
      if (typeof record0["txId"] !== "string") {
        return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["txId"])}`;
      }
    }
    const fieldPath0_1 = `${path}.query`;
    if (!_vdl.hasOwn(record0, "query") || record0["query"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["query"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["query"])}`;
    }
    const fieldPath0_2 = `${path}.params`;
    if (_vdl.hasOwn(record0, "params") && record0["params"] !== undefined) {
      if (!Array.isArray(record0["params"])) {
        return `${fieldPath0_2}: expected array, got ${_vdl.describeValue(record0["params"])}`;
      }
      for (let index1 = 0; index1 < record0["params"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_2}[${index1}]`;
        {
          const error = QueryParam.validate(
            record0["params"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated Query value into its runtime representation.
   */
  hydrate(input: Query): Query {
    return _vdl.withOptional(
      _vdl.withOptional(
        {
          query: input.query,
        },
        "txId",
        input.txId === undefined ? undefined : input.txId,
      ),
      "params",
      input.params === undefined
        ? undefined
        : input.params.map((item1) => QueryParam.hydrate(item1)),
    );
  },
} as const;

/**
 * QueryParam represents a generated VDL object.
 */
export type QueryParam = {
  /**
   * Parameter name for named parameters. Omitted for positional parameters.
   */
  name?: string;
  /**
   * The parameter value.
   */
  value: SqliteValue;
};

/**
 * QueryParam exposes the generated runtime helpers for QueryParam.
 */
export const QueryParam = {
  /**
   * Parses a JSON string into a validated and hydrated QueryParam value.
   */
  parse(json: string): QueryParam {
    const input = _vdl.parseJson(json);
    const error = QueryParam.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return QueryParam.hydrate(input as QueryParam);
  },

  /**
   * Performs structural validation for QueryParam (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "QueryParam"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.name`;
    if (_vdl.hasOwn(record0, "name") && record0["name"] !== undefined) {
      if (typeof record0["name"] !== "string") {
        return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["name"])}`;
      }
    }
    const fieldPath0_1 = `${path}.value`;
    if (!_vdl.hasOwn(record0, "value") || record0["value"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    {
      const error = SqliteValue.validate(record0["value"], fieldPath0_1);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated QueryParam value into its runtime representation.
   */
  hydrate(input: QueryParam): QueryParam {
    return _vdl.withOptional(
      {
        value: SqliteValue.hydrate(input.value),
      },
      "name",
      input.name === undefined ? undefined : input.name,
    );
  },
} as const;

/**
 * QueryResult represents a generated VDL object.
 */
export type QueryResult = {
  /**
   * The type of result (read, write, begin, commit, rollback, or error).
   */
  type: QueryResultType;
  /**
   * Query execution time in seconds (as a floating-point duration).
   */
  time: number;
  /**
   * Error message, present when type is "error".
   */
  error?: string;
  /**
   * Transaction ID, present when type is "begin".
   */
  txId?: string;
  /**
   * The rowid of the last inserted row, present for write results.
   */
  lastInsertId?: number;
  /**
   * The number of rows affected, present for write results.
   */
  rowsAffected?: number;
  /**
   * Column names for the returned rows, present for read/write results.
   */
  columns?: string[];
  /**
   * Storage class of each column for the returned rows.
   */
  types?: SqliteStorageClass[];
  /**
   * The returned rows, each row being an array of SqliteValue.
   */
  rows?: SqliteValue[][];
};

/**
 * QueryResult exposes the generated runtime helpers for QueryResult.
 */
export const QueryResult = {
  /**
   * Parses a JSON string into a validated and hydrated QueryResult value.
   */
  parse(json: string): QueryResult {
    const input = _vdl.parseJson(json);
    const error = QueryResult.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return QueryResult.hydrate(input as QueryResult);
  },

  /**
   * Performs structural validation for QueryResult (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "QueryResult"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.type`;
    if (!_vdl.hasOwn(record0, "type") || record0["type"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = QueryResultType.validate(record0["type"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.time`;
    if (!_vdl.hasOwn(record0, "time") || record0["time"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (
      typeof record0["time"] !== "number" ||
      !Number.isFinite(record0["time"])
    ) {
      return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["time"])}`;
    }
    const fieldPath0_2 = `${path}.error`;
    if (_vdl.hasOwn(record0, "error") && record0["error"] !== undefined) {
      if (typeof record0["error"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["error"])}`;
      }
    }
    const fieldPath0_3 = `${path}.txId`;
    if (_vdl.hasOwn(record0, "txId") && record0["txId"] !== undefined) {
      if (typeof record0["txId"] !== "string") {
        return `${fieldPath0_3}: expected string, got ${_vdl.describeValue(record0["txId"])}`;
      }
    }
    const fieldPath0_4 = `${path}.lastInsertId`;
    if (
      _vdl.hasOwn(record0, "lastInsertId") &&
      record0["lastInsertId"] !== undefined
    ) {
      if (
        typeof record0["lastInsertId"] !== "number" ||
        !Number.isFinite(record0["lastInsertId"])
      ) {
        return `${fieldPath0_4}: expected number, got ${_vdl.describeValue(record0["lastInsertId"])}`;
      }
    }
    const fieldPath0_5 = `${path}.rowsAffected`;
    if (
      _vdl.hasOwn(record0, "rowsAffected") &&
      record0["rowsAffected"] !== undefined
    ) {
      if (
        typeof record0["rowsAffected"] !== "number" ||
        !Number.isFinite(record0["rowsAffected"])
      ) {
        return `${fieldPath0_5}: expected number, got ${_vdl.describeValue(record0["rowsAffected"])}`;
      }
    }
    const fieldPath0_6 = `${path}.columns`;
    if (_vdl.hasOwn(record0, "columns") && record0["columns"] !== undefined) {
      if (!Array.isArray(record0["columns"])) {
        return `${fieldPath0_6}: expected array, got ${_vdl.describeValue(record0["columns"])}`;
      }
      for (let index1 = 0; index1 < record0["columns"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_6}[${index1}]`;
        if (typeof record0["columns"][index1] !== "string") {
          return `${itemPath1}: expected string, got ${_vdl.describeValue(record0["columns"][index1])}`;
        }
      }
    }
    const fieldPath0_7 = `${path}.types`;
    if (_vdl.hasOwn(record0, "types") && record0["types"] !== undefined) {
      if (!Array.isArray(record0["types"])) {
        return `${fieldPath0_7}: expected array, got ${_vdl.describeValue(record0["types"])}`;
      }
      for (let index1 = 0; index1 < record0["types"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_7}[${index1}]`;
        {
          const error = SqliteStorageClass.validate(
            record0["types"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    const fieldPath0_8 = `${path}.rows`;
    if (_vdl.hasOwn(record0, "rows") && record0["rows"] !== undefined) {
      if (!Array.isArray(record0["rows"])) {
        return `${fieldPath0_8}: expected array, got ${_vdl.describeValue(record0["rows"])}`;
      }
      for (let index1 = 0; index1 < record0["rows"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_8}[${index1}]`;
        if (!Array.isArray(record0["rows"][index1])) {
          return `${itemPath1}: expected array, got ${_vdl.describeValue(record0["rows"][index1])}`;
        }
        for (
          let index2 = 0;
          index2 < record0["rows"][index1].length;
          index2 += 1
        ) {
          const itemPath2 = `${itemPath1}[${index2}]`;
          {
            const error = SqliteValue.validate(
              record0["rows"][index1][index2],
              itemPath2,
            );
            if (error !== null) {
              return error;
            }
          }
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated QueryResult value into its runtime representation.
   */
  hydrate(input: QueryResult): QueryResult {
    return _vdl.withOptional(
      _vdl.withOptional(
        _vdl.withOptional(
          _vdl.withOptional(
            _vdl.withOptional(
              _vdl.withOptional(
                _vdl.withOptional(
                  {
                    type: QueryResultType.hydrate(input.type),
                    time: input.time,
                  },
                  "error",
                  input.error === undefined ? undefined : input.error,
                ),
                "txId",
                input.txId === undefined ? undefined : input.txId,
              ),
              "lastInsertId",
              input.lastInsertId === undefined ? undefined : input.lastInsertId,
            ),
            "rowsAffected",
            input.rowsAffected === undefined ? undefined : input.rowsAffected,
          ),
          "columns",
          input.columns === undefined
            ? undefined
            : input.columns.map((item1) => item1),
        ),
        "types",
        input.types === undefined
          ? undefined
          : input.types.map((item1) => SqliteStorageClass.hydrate(item1)),
      ),
      "rows",
      input.rows === undefined
        ? undefined
        : input.rows.map((item1) =>
            item1.map((item2) => SqliteValue.hydrate(item2)),
          ),
    );
  },
} as const;

/**
 * SqliteValue represents a generated VDL object.
 */
export type SqliteValue = {
  /**
   * SQL NULL value.
   */
  null?: boolean;
  /**
   * SQL INTEGER value.
   */
  integer?: number;
  /**
   * SQL REAL value.
   */
  real?: number;
  /**
   * SQL TEXT value.
   */
  text?: string;
  /**
   * SQL BLOB value encoded as base64.
   */
  blob?: string;
};

/**
 * SqliteValue exposes the generated runtime helpers for SqliteValue.
 */
export const SqliteValue = {
  /**
   * Parses a JSON string into a validated and hydrated SqliteValue value.
   */
  parse(json: string): SqliteValue {
    const input = _vdl.parseJson(json);
    const error = SqliteValue.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SqliteValue.hydrate(input as SqliteValue);
  },

  /**
   * Performs structural validation for SqliteValue (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SqliteValue"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.null`;
    if (_vdl.hasOwn(record0, "null") && record0["null"] !== undefined) {
      if (typeof record0["null"] !== "boolean") {
        return `${fieldPath0_0}: expected boolean, got ${_vdl.describeValue(record0["null"])}`;
      }
    }
    const fieldPath0_1 = `${path}.integer`;
    if (_vdl.hasOwn(record0, "integer") && record0["integer"] !== undefined) {
      if (
        typeof record0["integer"] !== "number" ||
        !Number.isFinite(record0["integer"])
      ) {
        return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["integer"])}`;
      }
    }
    const fieldPath0_2 = `${path}.real`;
    if (_vdl.hasOwn(record0, "real") && record0["real"] !== undefined) {
      if (
        typeof record0["real"] !== "number" ||
        !Number.isFinite(record0["real"])
      ) {
        return `${fieldPath0_2}: expected number, got ${_vdl.describeValue(record0["real"])}`;
      }
    }
    const fieldPath0_3 = `${path}.text`;
    if (_vdl.hasOwn(record0, "text") && record0["text"] !== undefined) {
      if (typeof record0["text"] !== "string") {
        return `${fieldPath0_3}: expected string, got ${_vdl.describeValue(record0["text"])}`;
      }
    }
    const fieldPath0_4 = `${path}.blob`;
    if (_vdl.hasOwn(record0, "blob") && record0["blob"] !== undefined) {
      if (typeof record0["blob"] !== "string") {
        return `${fieldPath0_4}: expected string, got ${_vdl.describeValue(record0["blob"])}`;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SqliteValue value into its runtime representation.
   */
  hydrate(input: SqliteValue): SqliteValue {
    return _vdl.withOptional(
      _vdl.withOptional(
        _vdl.withOptional(
          _vdl.withOptional(
            _vdl.withOptional(
              {},
              "null",
              input.null === undefined ? undefined : input.null,
            ),
            "integer",
            input.integer === undefined ? undefined : input.integer,
          ),
          "real",
          input.real === undefined ? undefined : input.real,
        ),
        "text",
        input.text === undefined ? undefined : input.text,
      ),
      "blob",
      input.blob === undefined ? undefined : input.blob,
    );
  },
} as const;

/**
 * Stats represents a generated VDL object.
 */
export type Stats = {
  /**
   * The server start time.
   */
  startedAt: Date;
  /**
   * Number of seconds since the server started.
   */
  uptimeSeconds: number;
  /**
   * Cumulative counters for all completed operations.
   */
  totals: StatsTotalsCounters;
  /**
   * Counters for currently queued or in-flight operations.
   */
  queued: StatsQueuedCounters;
  /**
   * Per-minute counters keyed by UTC minute in RFC3339 format.
   */
  minutes: Record<string, StatsTotalsCounters>;
};

/**
 * Stats exposes the generated runtime helpers for Stats.
 */
export const Stats = {
  /**
   * Parses a JSON string into a validated and hydrated Stats value.
   */
  parse(json: string): Stats {
    const input = _vdl.parseJson(json);
    const error = Stats.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Stats.hydrate(input as Stats);
  },

  /**
   * Performs structural validation for Stats (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Stats"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.startedAt`;
    if (
      !_vdl.hasOwn(record0, "startedAt") ||
      record0["startedAt"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (!_vdl.isValidDateInput(record0["startedAt"])) {
      return `${fieldPath0_0}: expected datetime string or Date, got ${_vdl.describeValue(record0["startedAt"])}`;
    }
    const fieldPath0_1 = `${path}.uptimeSeconds`;
    if (
      !_vdl.hasOwn(record0, "uptimeSeconds") ||
      record0["uptimeSeconds"] === undefined
    ) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (
      typeof record0["uptimeSeconds"] !== "number" ||
      !Number.isFinite(record0["uptimeSeconds"])
    ) {
      return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["uptimeSeconds"])}`;
    }
    const fieldPath0_2 = `${path}.totals`;
    if (!_vdl.hasOwn(record0, "totals") || record0["totals"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    {
      const error = StatsTotalsCounters.validate(
        record0["totals"],
        fieldPath0_2,
      );
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_3 = `${path}.queued`;
    if (!_vdl.hasOwn(record0, "queued") || record0["queued"] === undefined) {
      return `${fieldPath0_3}: required field is missing`;
    }
    {
      const error = StatsQueuedCounters.validate(
        record0["queued"],
        fieldPath0_3,
      );
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_4 = `${path}.minutes`;
    if (!_vdl.hasOwn(record0, "minutes") || record0["minutes"] === undefined) {
      return `${fieldPath0_4}: required field is missing`;
    }
    if (!_vdl.isRecord(record0["minutes"])) {
      return `${fieldPath0_4}: expected object, got ${_vdl.describeValue(record0["minutes"])}`;
    }
    for (const entry1 of _vdl.recordEntries(record0["minutes"])) {
      const key1 = entry1[0];
      const value1 = entry1[1];
      const valuePath1 = `${fieldPath0_4}[${JSON.stringify(key1)}]`;
      {
        const error = StatsTotalsCounters.validate(value1, valuePath1);
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated Stats value into its runtime representation.
   */
  hydrate(input: Stats): Stats {
    return {
      startedAt: _vdl.hydrateDateInput(input.startedAt),
      uptimeSeconds: input.uptimeSeconds,
      totals: StatsTotalsCounters.hydrate(input.totals),
      queued: StatsQueuedCounters.hydrate(input.queued),
      minutes: _vdl.mapRecord(input.minutes, (value1) =>
        StatsTotalsCounters.hydrate(value1),
      ),
    };
  },
} as const;

/**
 * StatsQueuedCounters represents a generated VDL object.
 */
export type StatsQueuedCounters = {
  /**
   * Number of BEGIN TRANSACTION statements currently queued.
   */
  begins: number;
  /**
   * Number of write queries currently queued.
   */
  writes: number;
  /**
   * Number of HTTP requests currently being processed or queued.
   */
  httpRequests: number;
};

/**
 * StatsQueuedCounters exposes the generated runtime helpers for StatsQueuedCounters.
 */
export const StatsQueuedCounters = {
  /**
   * Parses a JSON string into a validated and hydrated StatsQueuedCounters value.
   */
  parse(json: string): StatsQueuedCounters {
    const input = _vdl.parseJson(json);
    const error = StatsQueuedCounters.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return StatsQueuedCounters.hydrate(input as StatsQueuedCounters);
  },

  /**
   * Performs structural validation for StatsQueuedCounters (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "StatsQueuedCounters"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.begins`;
    if (!_vdl.hasOwn(record0, "begins") || record0["begins"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (
      typeof record0["begins"] !== "number" ||
      !Number.isFinite(record0["begins"])
    ) {
      return `${fieldPath0_0}: expected number, got ${_vdl.describeValue(record0["begins"])}`;
    }
    const fieldPath0_1 = `${path}.writes`;
    if (!_vdl.hasOwn(record0, "writes") || record0["writes"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (
      typeof record0["writes"] !== "number" ||
      !Number.isFinite(record0["writes"])
    ) {
      return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["writes"])}`;
    }
    const fieldPath0_2 = `${path}.httpRequests`;
    if (
      !_vdl.hasOwn(record0, "httpRequests") ||
      record0["httpRequests"] === undefined
    ) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (
      typeof record0["httpRequests"] !== "number" ||
      !Number.isFinite(record0["httpRequests"])
    ) {
      return `${fieldPath0_2}: expected number, got ${_vdl.describeValue(record0["httpRequests"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated StatsQueuedCounters value into its runtime representation.
   */
  hydrate(input: StatsQueuedCounters): StatsQueuedCounters {
    return {
      begins: input.begins,
      writes: input.writes,
      httpRequests: input.httpRequests,
    };
  },
} as const;

/**
 * StatsTotalsCounters represents a generated VDL object.
 */
export type StatsTotalsCounters = {
  /**
   * Total number of completed read queries.
   */
  reads: number;
  /**
   * Total number of completed write queries.
   */
  writes: number;
  /**
   * Total number of completed BEGIN TRANSACTION statements.
   */
  begins: number;
  /**
   * Total number of completed COMMIT statements.
   */
  commits: number;
  /**
   * Total number of completed ROLLBACK statements.
   */
  rollbacks: number;
  /**
   * Total number of queries that resulted in an error.
   */
  errors: number;
  /**
   * Total number of HTTP requests received.
   */
  httpRequests: number;
};

/**
 * StatsTotalsCounters exposes the generated runtime helpers for StatsTotalsCounters.
 */
export const StatsTotalsCounters = {
  /**
   * Parses a JSON string into a validated and hydrated StatsTotalsCounters value.
   */
  parse(json: string): StatsTotalsCounters {
    const input = _vdl.parseJson(json);
    const error = StatsTotalsCounters.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return StatsTotalsCounters.hydrate(input as StatsTotalsCounters);
  },

  /**
   * Performs structural validation for StatsTotalsCounters (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "StatsTotalsCounters"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.reads`;
    if (!_vdl.hasOwn(record0, "reads") || record0["reads"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (
      typeof record0["reads"] !== "number" ||
      !Number.isFinite(record0["reads"])
    ) {
      return `${fieldPath0_0}: expected number, got ${_vdl.describeValue(record0["reads"])}`;
    }
    const fieldPath0_1 = `${path}.writes`;
    if (!_vdl.hasOwn(record0, "writes") || record0["writes"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (
      typeof record0["writes"] !== "number" ||
      !Number.isFinite(record0["writes"])
    ) {
      return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["writes"])}`;
    }
    const fieldPath0_2 = `${path}.begins`;
    if (!_vdl.hasOwn(record0, "begins") || record0["begins"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (
      typeof record0["begins"] !== "number" ||
      !Number.isFinite(record0["begins"])
    ) {
      return `${fieldPath0_2}: expected number, got ${_vdl.describeValue(record0["begins"])}`;
    }
    const fieldPath0_3 = `${path}.commits`;
    if (!_vdl.hasOwn(record0, "commits") || record0["commits"] === undefined) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (
      typeof record0["commits"] !== "number" ||
      !Number.isFinite(record0["commits"])
    ) {
      return `${fieldPath0_3}: expected number, got ${_vdl.describeValue(record0["commits"])}`;
    }
    const fieldPath0_4 = `${path}.rollbacks`;
    if (
      !_vdl.hasOwn(record0, "rollbacks") ||
      record0["rollbacks"] === undefined
    ) {
      return `${fieldPath0_4}: required field is missing`;
    }
    if (
      typeof record0["rollbacks"] !== "number" ||
      !Number.isFinite(record0["rollbacks"])
    ) {
      return `${fieldPath0_4}: expected number, got ${_vdl.describeValue(record0["rollbacks"])}`;
    }
    const fieldPath0_5 = `${path}.errors`;
    if (!_vdl.hasOwn(record0, "errors") || record0["errors"] === undefined) {
      return `${fieldPath0_5}: required field is missing`;
    }
    if (
      typeof record0["errors"] !== "number" ||
      !Number.isFinite(record0["errors"])
    ) {
      return `${fieldPath0_5}: expected number, got ${_vdl.describeValue(record0["errors"])}`;
    }
    const fieldPath0_6 = `${path}.httpRequests`;
    if (
      !_vdl.hasOwn(record0, "httpRequests") ||
      record0["httpRequests"] === undefined
    ) {
      return `${fieldPath0_6}: required field is missing`;
    }
    if (
      typeof record0["httpRequests"] !== "number" ||
      !Number.isFinite(record0["httpRequests"])
    ) {
      return `${fieldPath0_6}: expected number, got ${_vdl.describeValue(record0["httpRequests"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated StatsTotalsCounters value into its runtime representation.
   */
  hydrate(input: StatsTotalsCounters): StatsTotalsCounters {
    return {
      reads: input.reads,
      writes: input.writes,
      begins: input.begins,
      commits: input.commits,
      rollbacks: input.rollbacks,
      errors: input.errors,
      httpRequests: input.httpRequests,
    };
  },
} as const;

/**
 * System represents a generated VDL object.
 */
export type System = {
  /**
   * Checks whether the server can perform a basic database read.
   */
  health: SystemHealth;
  /**
   * Returns the authentication role for the current session.
   */
  session: SystemSession;
  /**
   * Returns server information and runtime statistics.
   */
  status: SystemStatus;
};

/**
 * System exposes the generated runtime helpers for System.
 */
export const System = {
  /**
   * Parses a JSON string into a validated and hydrated System value.
   */
  parse(json: string): System {
    const input = _vdl.parseJson(json);
    const error = System.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return System.hydrate(input as System);
  },

  /**
   * Performs structural validation for System (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "System"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.health`;
    if (!_vdl.hasOwn(record0, "health") || record0["health"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = SystemHealth.validate(record0["health"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.session`;
    if (!_vdl.hasOwn(record0, "session") || record0["session"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    {
      const error = SystemSession.validate(record0["session"], fieldPath0_1);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_2 = `${path}.status`;
    if (!_vdl.hasOwn(record0, "status") || record0["status"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    {
      const error = SystemStatus.validate(record0["status"], fieldPath0_2);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated System value into its runtime representation.
   */
  hydrate(input: System): System {
    return {
      health: SystemHealth.hydrate(input.health),
      session: SystemSession.hydrate(input.session),
      status: SystemStatus.hydrate(input.status),
    };
  },
} as const;

/**
 * SystemHealth represents a generated VDL object.
 */
export type SystemHealth = {
  output: SystemHealthOutput;
};

/**
 * SystemHealth exposes the generated runtime helpers for SystemHealth.
 */
export const SystemHealth = {
  /**
   * Parses a JSON string into a validated and hydrated SystemHealth value.
   */
  parse(json: string): SystemHealth {
    const input = _vdl.parseJson(json);
    const error = SystemHealth.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemHealth.hydrate(input as SystemHealth);
  },

  /**
   * Performs structural validation for SystemHealth (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemHealth"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.output`;
    if (!_vdl.hasOwn(record0, "output") || record0["output"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = SystemHealthOutput.validate(
        record0["output"],
        fieldPath0_0,
      );
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SystemHealth value into its runtime representation.
   */
  hydrate(input: SystemHealth): SystemHealth {
    return {
      output: SystemHealthOutput.hydrate(input.output),
    };
  },
} as const;

/**
 * SystemHealthOutput represents a generated VDL object.
 */
export type SystemHealthOutput = {
  /**
   * Whether the server is healthy and fully operational.
   */
  healthy: boolean;
  /**
   * Whether the database is reachable and responsive.
   */
  database: boolean;
  /**
   * A human-readable message describing the health state.
   */
  message: string;
};

/**
 * SystemHealthOutput exposes the generated runtime helpers for SystemHealthOutput.
 */
export const SystemHealthOutput = {
  /**
   * Parses a JSON string into a validated and hydrated SystemHealthOutput value.
   */
  parse(json: string): SystemHealthOutput {
    const input = _vdl.parseJson(json);
    const error = SystemHealthOutput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemHealthOutput.hydrate(input as SystemHealthOutput);
  },

  /**
   * Performs structural validation for SystemHealthOutput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemHealthOutput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.healthy`;
    if (!_vdl.hasOwn(record0, "healthy") || record0["healthy"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["healthy"] !== "boolean") {
      return `${fieldPath0_0}: expected boolean, got ${_vdl.describeValue(record0["healthy"])}`;
    }
    const fieldPath0_1 = `${path}.database`;
    if (
      !_vdl.hasOwn(record0, "database") ||
      record0["database"] === undefined
    ) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["database"] !== "boolean") {
      return `${fieldPath0_1}: expected boolean, got ${_vdl.describeValue(record0["database"])}`;
    }
    const fieldPath0_2 = `${path}.message`;
    if (!_vdl.hasOwn(record0, "message") || record0["message"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (typeof record0["message"] !== "string") {
      return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["message"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated SystemHealthOutput value into its runtime representation.
   */
  hydrate(input: SystemHealthOutput): SystemHealthOutput {
    return {
      healthy: input.healthy,
      database: input.database,
      message: input.message,
    };
  },
} as const;

/**
 * SystemSession represents a generated VDL object.
 */
export type SystemSession = {
  output: SystemSessionOutput;
};

/**
 * SystemSession exposes the generated runtime helpers for SystemSession.
 */
export const SystemSession = {
  /**
   * Parses a JSON string into a validated and hydrated SystemSession value.
   */
  parse(json: string): SystemSession {
    const input = _vdl.parseJson(json);
    const error = SystemSession.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemSession.hydrate(input as SystemSession);
  },

  /**
   * Performs structural validation for SystemSession (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemSession"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.output`;
    if (!_vdl.hasOwn(record0, "output") || record0["output"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = SystemSessionOutput.validate(
        record0["output"],
        fieldPath0_0,
      );
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SystemSession value into its runtime representation.
   */
  hydrate(input: SystemSession): SystemSession {
    return {
      output: SystemSessionOutput.hydrate(input.output),
    };
  },
} as const;

/**
 * SystemSessionOutput represents a generated VDL object.
 */
export type SystemSessionOutput = {
  /**
   * The authentication role assigned to the current session.
   */
  role: AuthRole;
};

/**
 * SystemSessionOutput exposes the generated runtime helpers for SystemSessionOutput.
 */
export const SystemSessionOutput = {
  /**
   * Parses a JSON string into a validated and hydrated SystemSessionOutput value.
   */
  parse(json: string): SystemSessionOutput {
    const input = _vdl.parseJson(json);
    const error = SystemSessionOutput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemSessionOutput.hydrate(input as SystemSessionOutput);
  },

  /**
   * Performs structural validation for SystemSessionOutput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemSessionOutput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.role`;
    if (!_vdl.hasOwn(record0, "role") || record0["role"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = AuthRole.validate(record0["role"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SystemSessionOutput value into its runtime representation.
   */
  hydrate(input: SystemSessionOutput): SystemSessionOutput {
    return {
      role: AuthRole.hydrate(input.role),
    };
  },
} as const;

/**
 * SystemStatus represents a generated VDL object.
 */
export type SystemStatus = {
  output: SystemStatusOutput;
};

/**
 * SystemStatus exposes the generated runtime helpers for SystemStatus.
 */
export const SystemStatus = {
  /**
   * Parses a JSON string into a validated and hydrated SystemStatus value.
   */
  parse(json: string): SystemStatus {
    const input = _vdl.parseJson(json);
    const error = SystemStatus.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemStatus.hydrate(input as SystemStatus);
  },

  /**
   * Performs structural validation for SystemStatus (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemStatus"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.output`;
    if (!_vdl.hasOwn(record0, "output") || record0["output"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = SystemStatusOutput.validate(
        record0["output"],
        fieldPath0_0,
      );
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SystemStatus value into its runtime representation.
   */
  hydrate(input: SystemStatus): SystemStatus {
    return {
      output: SystemStatusOutput.hydrate(input.output),
    };
  },
} as const;

/**
 * SystemStatusOutput represents a generated VDL object.
 */
export type SystemStatusOutput = {
  /**
   * The server name.
   */
  name: string;
  /**
   * The server version string.
   */
  version: string;
  /**
   * Current runtime statistics.
   */
  stats: Stats;
};

/**
 * SystemStatusOutput exposes the generated runtime helpers for SystemStatusOutput.
 */
export const SystemStatusOutput = {
  /**
   * Parses a JSON string into a validated and hydrated SystemStatusOutput value.
   */
  parse(json: string): SystemStatusOutput {
    const input = _vdl.parseJson(json);
    const error = SystemStatusOutput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return SystemStatusOutput.hydrate(input as SystemStatusOutput);
  },

  /**
   * Performs structural validation for SystemStatusOutput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "SystemStatusOutput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_1 = `${path}.version`;
    if (!_vdl.hasOwn(record0, "version") || record0["version"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["version"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["version"])}`;
    }
    const fieldPath0_2 = `${path}.stats`;
    if (!_vdl.hasOwn(record0, "stats") || record0["stats"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    {
      const error = Stats.validate(record0["stats"], fieldPath0_2);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated SystemStatusOutput value into its runtime representation.
   */
  hydrate(input: SystemStatusOutput): SystemStatusOutput {
    return {
      name: input.name,
      version: input.version,
      stats: Stats.hydrate(input.stats),
    };
  },
} as const;

/**
 * Internal helpers shared by the generated runtime namespaces in this file.
 */
const _vdl = {
  /**
   * Parses JSON text and wraps syntax failures in a stable generated error message.
   */
  parseJson(json: string): unknown {
    try {
      return JSON.parse(json);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Invalid JSON input: ${message}`);
    }
  },

  /**
   * Returns own enumerable entries from a record in insertion order.
   */
  recordEntries<TValue>(
    record: Record<string, TValue>,
  ): Array<[string, TValue]> {
    const entries: Array<[string, TValue]> = [];
    for (const key in record) {
      if (Object.prototype.hasOwnProperty.call(record, key)) {
        const value = record[key] as TValue;
        entries.push([key, value]);
      }
    }
    return entries;
  },

  /**
   * Creates a new record by mapping every own enumerable value.
   */
  mapRecord<TInput, TOutput>(
    record: Record<string, TInput>,
    mapValue: (value: TInput) => TOutput,
  ): Record<string, TOutput> {
    const output: Record<string, TOutput> = {};
    for (const key in record) {
      if (Object.prototype.hasOwnProperty.call(record, key)) {
        const value = record[key] as TInput;
        output[key] = mapValue(value);
      }
    }
    return output;
  },

  /**
   * Adds an optional property only when the value is defined.
   */
  withOptional<TRecord extends object, TKey extends string, TValue>(
    record: TRecord,
    key: TKey,
    value: TValue | undefined,
  ): TRecord & Partial<Record<TKey, TValue>> {
    const mutable = record as Record<string, unknown>;
    if (value !== undefined) {
      mutable[key] = value;
    }
    return record as TRecord & Partial<Record<TKey, TValue>>;
  },

  /**
   * Checks whether a value can be validated as a plain object record.
   */
  isRecord(value: unknown): value is Record<string, unknown> {
    return (
      typeof value === "object" &&
      value !== null &&
      !Array.isArray(value) &&
      !(value instanceof Date)
    );
  },

  /**
   * Checks whether a record defines a property directly on the current object.
   */
  hasOwn(record: Record<string, unknown>, key: string): boolean {
    return Object.prototype.hasOwnProperty.call(record, key);
  },

  /**
   * Describes an input value using the categories reported by generated validation errors.
   */
  describeValue(value: unknown): string {
    if (value === null) {
      return "null";
    }
    if (Array.isArray(value)) {
      return "array";
    }
    if (value instanceof Date) {
      return "Date";
    }
    return typeof value;
  },

  /**
   * Checks whether an input can be hydrated into a valid Date instance.
   */
  isValidDateInput(value: unknown): value is string | Date {
    if (value instanceof Date) {
      return !Number.isNaN(value.getTime());
    }
    if (typeof value !== "string") {
      return false;
    }
    return !Number.isNaN(new Date(value).getTime());
  },

  /**
   * Hydrates a string or Date input into a fresh Date instance.
   */
  hydrateDateInput(value: string | Date): Date {
    return value instanceof Date ? new Date(value.getTime()) : new Date(value);
  },
} as const;
